"use client"

import {
  Brain,
  Calculator,
  Crown,
  Scale,
  Sigma,
  ShieldCheck,
  Target,
  TrendingUp,
} from "lucide-react"
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"

const attributeGroups = [
  {
    key: "physical",
    title: "Physical Attributes (8)",
    attributes: [
      "heightCm",
      "reachCm",
      "weightClassAlignment",
      "handSpeed",
      "footSpeed",
      "strength",
      "endurance",
      "reactionTime",
    ],
  },
  {
    key: "technical",
    title: "Technical Attributes (7)",
    attributes: [
      "punchAccuracy",
      "punchVariety",
      "defensiveGuardEfficiency",
      "headMovement",
      "footworkTechnique",
      "counterpunchingAbility",
      "combinationEfficiency",
    ],
  },
  {
    key: "tactical",
    title: "Tactical Attributes (6)",
    attributes: [
      "ringIq",
      "adaptabilityMidFight",
      "distanceControl",
      "tempoControl",
      "opponentPatternRecognition",
      "fightPlanningDiscipline",
    ],
  },
  {
    key: "psychological",
    title: "Psychological Attributes (5)",
    attributes: [
      "composureUnderPressure",
      "aggressionControl",
      "mentalToughness",
      "focusConsistency",
      "resilienceAfterKnockdown",
    ],
  },
  {
    key: "experience",
    title: "Experience & Performance Attributes (6)",
    attributes: [
      "winRatio",
      "knockoutRatio",
      "titleFightExperience",
      "strengthOfOpposition",
      "recentFightActivity",
      "performanceConsistency",
    ],
  },
]

function AttributeChip({ name }: { name: string }) {
  return (
      <div className="rounded-md bg-secondary px-3 py-2 text-xs text-foreground">
        {name}
      </div>
  )
}

function FormulaCard({
                       title,
                       formula,
                       description,
                     }: {
  title: string
  formula: string
  description: string
}) {
  return (
      <div className="rounded-lg border border-border bg-secondary/40 p-4">
        <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
          {title}
        </p>
        <p className="mt-2 whitespace-pre-wrap font-mono text-xs text-foreground">
          {formula}
        </p>
        <p className="mt-2 text-xs text-muted-foreground">{description}</p>
      </div>
  )
}

export default function ModelPage() {
  return (
      <div className="space-y-6">
        <div>
          <h1 className="font-display text-2xl font-bold text-foreground">
            Model Explanation
          </h1>
          <p className="mt-1 text-sm text-muted-foreground">
            Understand the attribute system, perfect boxer model, normalization,
            scoring, closeness, confidence adjustment, and prediction logic.
          </p>
        </div>

        <Accordion
            type="multiple"
            defaultValue={[
              "perfect-boxer",
              "attributes",
              "normalization",
              "scoring",
              "closeness",
              "confidence",
              "probability",
            ]}
            className="space-y-3"
        >
          <AccordionItem value="perfect-boxer" className="rounded-xl border bg-card px-5">
            <AccordionTrigger className="py-4">
              <div className="flex items-center gap-3">
                <Crown className="size-4 text-primary" />
                <div>
                  <p className="text-sm font-semibold">Perfect Boxer Model</p>
                  <p className="text-xs text-muted-foreground">
                    Built from real top-ranked fighters
                  </p>
                </div>
              </div>
            </AccordionTrigger>

            <AccordionContent className="space-y-3 pb-5 text-sm text-muted-foreground">
              <p>
                The perfect boxer is created by taking the top ranked boxers
                generated by AI for a specific weight class and averaging their
                attributes.
              </p>
              <p>
                This means each weight class has its own benchmark based on real
                historical performance, not a theoretical perfect fighter.
              </p>
            </AccordionContent>
          </AccordionItem>

          <AccordionItem value="attributes" className="rounded-xl border bg-card px-5">
            <AccordionTrigger className="py-4">
              <div className="flex items-center gap-3">
                <Scale className="size-4 text-accent" />
                <p className="text-sm font-semibold">Attributes</p>
              </div>
            </AccordionTrigger>

            <AccordionContent className="space-y-4 pb-5">
              {attributeGroups.map((group) => (
                  <div key={group.key}>
                    <p className="text-sm font-semibold">{group.title}</p>
                    <div className="mt-2 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">
                      {group.attributes.map((a) => (
                          <AttributeChip key={a} name={a} />
                      ))}
                    </div>
                  </div>
              ))}
            </AccordionContent>
          </AccordionItem>

          <AccordionItem value="normalization" className="rounded-xl border bg-card px-5">
            <AccordionTrigger className="py-4">
              <div className="flex items-center gap-3">
                <Calculator className="size-4 text-primary" />
                <p className="text-sm font-semibold">Normalization</p>
              </div>
            </AccordionTrigger>

            <AccordionContent className="space-y-4 pb-5 text-sm text-muted-foreground">
              <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
                <FormulaCard
                    title="Measurements"
                    formula={`m(x) = (x - min) / (max - min)`}
                    description="Used for height and reach. These are normalized dynamically against the ranked boxer range for the active batch."
                />
                <FormulaCard
                    title="Rubric Scores"
                    formula={`s(x) = (x - 1) / 9`}
                    description="Used for scored attributes on the 1–10 scale."
                />
                <FormulaCard
                    title="Ratios"
                    formula={`r(x) = clamp(x, 0, 1)`}
                    description="Used for winRatio and knockoutRatio."
                />
              </div>
            </AccordionContent>
          </AccordionItem>

          <AccordionItem value="scoring" className="rounded-xl border bg-card px-5">
            <AccordionTrigger className="py-4">
              <div className="flex items-center gap-3">
                <Sigma className="size-4 text-accent" />
                <p className="text-sm font-semibold">Scoring</p>
              </div>
            </AccordionTrigger>

            <AccordionContent className="space-y-4 pb-5 text-sm text-muted-foreground">
              <div className="grid gap-4 md:grid-cols-2">
                <FormulaCard
                    title="Category Score"
                    formula={`C = Σ (wᵢ · Aᵢ)

wᵢ = W_category / n`}
                    description="Each attribute is equally weighted within its category, where n is the number of attributes in that category."
                />

                <FormulaCard
                    title="Overall Score"
                    formula={`O = physical + technical + tactical + psychological + experience`}
                    description="Overall score is the sum of the five category scores."
                />
              </div>
            </AccordionContent>
          </AccordionItem>

          <AccordionItem value="closeness" className="rounded-xl border bg-card px-5">
            <AccordionTrigger className="py-4">
              <div className="flex items-center gap-3">
                <Target className="size-4 text-primary" />
                <p className="text-sm font-semibold">Base Closeness</p>
              </div>
            </AccordionTrigger>

            <AccordionContent className="space-y-4 pb-5 text-sm text-muted-foreground whitespace-pre-line">
              <FormulaCard
                  title="Base Closeness Calculation"
                  formula={`distance = |physical_f - physical_p|
         + |technical_f - technical_p|
         + |tactical_f - tactical_p|
         + |psychological_f - psychological_p|
         + |experience_f - experience_p|

baseCloseness = 1 - (distance / totalWeight)`}
                  description={`The fighter is compared to the perfect boxer using category scores.

totalWeight = physicalWeight + technicalWeight + tacticalWeight + psychologicalWeight + experienceWeight

Base closeness ranges from 0 to 1:
- 1 → identical to perfect boxer
- 0 → maximally different`}
              />
            </AccordionContent>
          </AccordionItem>

          <AccordionItem value="confidence" className="rounded-xl border bg-card px-5">
            <AccordionTrigger className="py-4">
              <div className="flex items-center gap-3">
                <ShieldCheck className="size-4 text-accent" />
                <p className="text-sm font-semibold">Attribute Confidence Adjustment</p>
              </div>
            </AccordionTrigger>

            <AccordionContent className="space-y-4 pb-5 text-sm text-muted-foreground whitespace-pre-line">
              <FormulaCard
                  title="Confidence-Adjusted Closeness"
                  formula={`adjustedCloseness = 0.5 + confidence · (baseCloseness - 0.5)`}
                  description={`Confidence is applied after base closeness is calculated.

This means confidence does not change the fighter's raw category scores.
Instead, it adjusts how strongly the system trusts the base closeness value.

Examples:
- confidence = 1.0 → no change
- confidence = 0.0 → adjusted closeness becomes 0.5 (neutral)
- lower confidence pulls the fighter closer to neutral uncertainty`}
              />
            </AccordionContent>
          </AccordionItem>

          <AccordionItem value="probability" className="rounded-xl border bg-card px-5">
            <AccordionTrigger className="py-4">
              <div className="flex items-center gap-3">
                <TrendingUp className="size-4 text-accent" />
                <p className="text-sm font-semibold">Probability</p>
              </div>
            </AccordionTrigger>

            <AccordionContent className="space-y-4 pb-5 text-sm text-muted-foreground whitespace-pre-line">
              <FormulaCard
                  title="Win Probability Calculation"
                  formula={`adjustedA = (adjustedClosenessA)³
adjustedB = (adjustedClosenessB)³

P(A) = adjustedA / (adjustedA + adjustedB)
P(B) = adjustedB / (adjustedA + adjustedB)`}
                  description={`The probability step uses confidence-adjusted closeness, not base closeness.

The exponent (³) increases separation between fighters:
- small differences become more meaningful
- the stronger fighter gains a clearer edge

Final probabilities are normalized so:
P(A) + P(B) = 1`}
              />
            </AccordionContent>
          </AccordionItem>
        </Accordion>

        <div className="rounded-xl border bg-card p-6">
          <div className="flex items-start gap-4">
            <Brain className="size-5 text-primary" />
            <p className="text-sm text-muted-foreground">
              This model provides structured predictions but cannot account for all
              real-world factors such as injuries, strategy changes, referee
              intervention, or randomness during a fight.
            </p>
          </div>
        </div>
      </div>
  )
}