"use client"

import {
  Brain,
  Calculator,
  Crown,
  Scale,
  Sigma,
  Target,
  TrendingUp,
} from "lucide-react"
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"

const attributeGroups = [
  {
    key: "physical",
    title: "Physical Attributes (8)",
    attributes: [
      "heightCm",
      "reachCm",
      "weightClassAlignment",
      "handSpeed",
      "footSpeed",
      "strength",
      "endurance",
      "reactionTime",
    ],
  },
  {
    key: "technical",
    title: "Technical Attributes (7)",
    attributes: [
      "punchAccuracy",
      "punchVariety",
      "defensiveGuardEfficiency",
      "headMovement",
      "footworkTechnique",
      "counterpunchingAbility",
      "combinationEfficiency",
    ],
  },
  {
    key: "tactical",
    title: "Tactical Attributes (6)",
    attributes: [
      "ringIq",
      "adaptabilityMidFight",
      "distanceControl",
      "tempoControl",
      "opponentPatternRecognition",
      "fightPlanningDiscipline",
    ],
  },
  {
    key: "psychological",
    title: "Psychological Attributes (5)",
    attributes: [
      "composureUnderPressure",
      "aggressionControl",
      "mentalToughness",
      "focusConsistency",
      "resilienceAfterKnockdown",
    ],
  },
  {
    key: "experience",
    title: "Experience & Performance Attributes (6)",
    attributes: [
      "winRatio",
      "knockoutRatio",
      "titleFightExperience",
      "strengthOfOpposition",
      "recentFightActivity",
      "performanceConsistency",
    ],
  },
]

function AttributeChip({ name }: { name: string }) {
  return (
      <div className="rounded-md bg-secondary px-3 py-2 text-xs text-foreground">
        {name}
      </div>
  )
}

function FormulaCard({
                       title,
                       formula,
                       description,
                     }: {
  title: string
  formula: string
  description: string
}) {
  return (
      <div className="rounded-lg border border-border bg-secondary/40 p-4">
        <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
          {title}
        </p>
        <p className="mt-2 font-mono text-xs text-foreground whitespace-pre-wrap">
          {formula}
        </p>
        <p className="mt-2 text-xs text-muted-foreground">{description}</p>
      </div>
  )
}

export default function ModelPage() {
  return (
      <div className="space-y-6">
        <div>
          <h1 className="font-display text-2xl font-bold text-foreground">
            Model Explanation
          </h1>
          <p className="mt-1 text-sm text-muted-foreground">
            Understand the attribute system, perfect boxer model, normalization,
            scoring, and prediction logic.
          </p>
        </div>

        <Accordion
            type="multiple"
            defaultValue={[
              "perfect-boxer",
              "attributes",
              "normalization",
              "scoring",
              "closeness",
              "probability",
            ]}
            className="space-y-3"
        >

          {/* PERFECT BOXER */}
          <AccordionItem value="perfect-boxer" className="rounded-xl border bg-card px-5">
            <AccordionTrigger className="py-4">
              <div className="flex items-center gap-3">
                <Crown className="size-4 text-primary" />
                <div>
                  <p className="text-sm font-semibold">Perfect Boxer Model</p>
                  <p className="text-xs text-muted-foreground">
                    Built from real top-ranked fighters
                  </p>
                </div>
              </div>
            </AccordionTrigger>

            <AccordionContent className="pb-5 space-y-3 text-sm text-muted-foreground">
              <p>
                The perfect boxer is created by taking the top ranked boxers
                generated by AI for a specific weight class and averaging their attributes.
              </p>
              <p>
                This means each weight class has its own benchmark based on real historical
                performance, not a theoretical perfect fighter.
              </p>
            </AccordionContent>
          </AccordionItem>

          {/* ATTRIBUTES */}
          <AccordionItem value="attributes" className="rounded-xl border bg-card px-5">
            <AccordionTrigger className="py-4">
              <div className="flex items-center gap-3">
                <Scale className="size-4 text-accent" />
                <p className="text-sm font-semibold">Attributes</p>
              </div>
            </AccordionTrigger>

            <AccordionContent className="pb-5 space-y-4">
              {attributeGroups.map((group) => (
                  <div key={group.key}>
                    <p className="text-sm font-semibold">{group.title}</p>
                    <div className="grid gap-2 mt-2 sm:grid-cols-2 lg:grid-cols-3">
                      {group.attributes.map((a) => (
                          <AttributeChip key={a} name={a} />
                      ))}
                    </div>
                  </div>
              ))}
            </AccordionContent>
          </AccordionItem>

          {/* NORMALIZATION */}
          <AccordionItem value="normalization" className="rounded-xl border bg-card px-5">
            <AccordionTrigger className="py-4">
              <div className="flex items-center gap-3">
                <Calculator className="size-4 text-primary" />
                <p className="text-sm font-semibold">Normalization</p>
              </div>
            </AccordionTrigger>

            <AccordionContent className="pb-5 space-y-4 text-sm text-muted-foreground">
              <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
                <FormulaCard
                    title="Measurements"
                    formula={`m(x) = (x - min) / (max - min)`}
                    description="Used for height and reach."
                />
                <FormulaCard
                    title="Rubric Scores"
                    formula={`s(x) = (x - 1) / 9`}
                    description="Used for 1–10 attributes."
                />
                <FormulaCard
                    title="Ratios"
                    formula={`r(x) = clamp(x, 0, 1)`}
                    description="Used for winRatio and knockoutRatio."
                />
              </div>
            </AccordionContent>
          </AccordionItem>

          {/* SCORING */}
          <AccordionItem value="scoring" className="rounded-xl border bg-card px-5">
            <AccordionTrigger className="py-4">
              <div className="flex items-center gap-3">
                <Sigma className="size-4 text-accent" />
                <p className="text-sm font-semibold">Scoring</p>
              </div>
            </AccordionTrigger>

            <AccordionContent className="pb-5 space-y-4 text-sm text-muted-foreground">
              <div className="grid gap-4 md:grid-cols-2">
                <FormulaCard
                    title="Category Score"
                    formula={`C = Σ (wᵢ · Aᵢ)

wᵢ = W_category / n,  with n being the number of attributes for that category`}
                    description="Each attribute is equally weighted within its category."
                />

                <FormulaCard
                    title="Overall Score"
                    formula={`O = Σ Cᵢ`}
                    description="Sum of all category scores."
                />
              </div>
            </AccordionContent>
          </AccordionItem>

          {/* CLOSENESS */}
          <AccordionItem value="closeness" className="rounded-xl border bg-card px-5">
            <AccordionTrigger className="py-4">
              <div className="flex items-center gap-3">
                <Target className="size-4 text-primary" />
                <p className="text-sm font-semibold">Closeness</p>
              </div>
            </AccordionTrigger>

            <AccordionContent className="pb-5 space-y-4 text-sm text-muted-foreground">
              <FormulaCard
                  title="Closeness Formula"
                  formula={`distance = Σ | Cᵢ (fighter) - Cᵢ (perfect) |

closeness = 1 - (distance / Σ Wᵢ)`}
                  description="Measures similarity to the perfect boxer."
              />
            </AccordionContent>
          </AccordionItem>

          {/* PROBABILITY */}
          <AccordionItem value="probability" className="rounded-xl border bg-card px-5">
            <AccordionTrigger className="py-4">
              <div className="flex items-center gap-3">
                <TrendingUp className="size-4 text-accent" />
                <p className="text-sm font-semibold">Probability</p>
              </div>
            </AccordionTrigger>

            <AccordionContent className="pb-5 space-y-4 text-sm text-muted-foreground">
              <FormulaCard
                  title="Probability"
                  formula={`adjusted = closeness^3

P(A) = A / (A + B)`}
                  description="Higher closeness leads to higher win probability."
              />
            </AccordionContent>
          </AccordionItem>
        </Accordion>

        <div className="rounded-xl border bg-card p-6">
          <div className="flex items-start gap-4">
            <Brain className="size-5 text-primary" />
            <p className="text-sm text-muted-foreground">
              This model provides structured predictions but cannot account for all real-world
              factors such as injuries, strategy changes, or randomness.
            </p>
          </div>
        </div>
      </div>
  )
}