/* tslint:disable */
/* eslint-disable */
/**
 * Nexus Boxing API
 * REST API for authentication, all time ranked boxers, perfect boxer generation, updating category weights, making predictions, managing prediction histories, and weight classes.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AllTimeRankedBoxerResponse,
  AllTimeRankedBoxerUpdateRequest,
  AllTimeRankedBoxerWithBatchStatusResponse,
  ApiErrorResponse,
  BoxerProfileLookupFailureResponse,
  GenerateBoxerRequest,
  GeneratedBoxerResponse,
} from '../models/index';
import {
    AllTimeRankedBoxerResponseFromJSON,
    AllTimeRankedBoxerResponseToJSON,
    AllTimeRankedBoxerUpdateRequestFromJSON,
    AllTimeRankedBoxerUpdateRequestToJSON,
    AllTimeRankedBoxerWithBatchStatusResponseFromJSON,
    AllTimeRankedBoxerWithBatchStatusResponseToJSON,
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    BoxerProfileLookupFailureResponseFromJSON,
    BoxerProfileLookupFailureResponseToJSON,
    GenerateBoxerRequestFromJSON,
    GenerateBoxerRequestToJSON,
    GeneratedBoxerResponseFromJSON,
    GeneratedBoxerResponseToJSON,
} from '../models/index';

export interface GenerateBoxerOperationRequest {
    generateBoxerRequest: GenerateBoxerRequest;
}

export interface GetActiveByWeightClassId1Request {
    weightClassId: number;
}

export interface GetByBatchIdRequest {
    batchId: number;
}

export interface GetByIdRequest {
    id: number;
}

export interface GetByWeightClassId1Request {
    weightClassId: number;
}

export interface UpdateRequest {
    id: number;
    allTimeRankedBoxerUpdateRequest: AllTimeRankedBoxerUpdateRequest;
}

/**
 * 
 */
export class AllTimeRankedBoxersApi extends runtime.BaseAPI {

    /**
     * Creates request options for generateBoxer without sending the request
     */
    async generateBoxerRequestOpts(requestParameters: GenerateBoxerOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['generateBoxerRequest'] == null) {
            throw new runtime.RequiredError(
                'generateBoxerRequest',
                'Required parameter "generateBoxerRequest" was null or undefined when calling generateBoxer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/all-time-ranked-boxers/generate-boxer`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GenerateBoxerRequestToJSON(requestParameters['generateBoxerRequest']),
        };
    }

    /**
     * Generates a boxer attribute profile for a boxer name and weight class using AI. Requires a valid Bearer JWT.
     * Generate boxer with AI
     */
    async generateBoxerRaw(requestParameters: GenerateBoxerOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GeneratedBoxerResponse>> {
        const requestOptions = await this.generateBoxerRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GeneratedBoxerResponseFromJSON(jsonValue));
    }

    /**
     * Generates a boxer attribute profile for a boxer name and weight class using AI. Requires a valid Bearer JWT.
     * Generate boxer with AI
     */
    async generateBoxer(requestParameters: GenerateBoxerOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GeneratedBoxerResponse> {
        const response = await this.generateBoxerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getActiveByWeightClassId1 without sending the request
     */
    async getActiveByWeightClassId1RequestOpts(requestParameters: GetActiveByWeightClassId1Request): Promise<runtime.RequestOpts> {
        if (requestParameters['weightClassId'] == null) {
            throw new runtime.RequiredError(
                'weightClassId',
                'Required parameter "weightClassId" was null or undefined when calling getActiveByWeightClassId1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/all-time-ranked-boxers/active/weight-class/{weightClassId}`;
        urlPath = urlPath.replace(`{${"weightClassId"}}`, encodeURIComponent(String(requestParameters['weightClassId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the ranked boxers in the active batch currently used to calculate the perfect boxer for that weight class.
     * Get active ranked boxers by weight class ID
     */
    async getActiveByWeightClassId1Raw(requestParameters: GetActiveByWeightClassId1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AllTimeRankedBoxerResponse>>> {
        const requestOptions = await this.getActiveByWeightClassId1RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AllTimeRankedBoxerResponseFromJSON));
    }

    /**
     * Returns the ranked boxers in the active batch currently used to calculate the perfect boxer for that weight class.
     * Get active ranked boxers by weight class ID
     */
    async getActiveByWeightClassId1(requestParameters: GetActiveByWeightClassId1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AllTimeRankedBoxerResponse>> {
        const response = await this.getActiveByWeightClassId1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAllActive without sending the request
     */
    async getAllActiveRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/all-time-ranked-boxers/active`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns all ranked boxers from all active batches across all weight classes.
     * Get all active ranked boxers
     */
    async getAllActiveRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AllTimeRankedBoxerResponse>>> {
        const requestOptions = await this.getAllActiveRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AllTimeRankedBoxerResponseFromJSON));
    }

    /**
     * Returns all ranked boxers from all active batches across all weight classes.
     * Get all active ranked boxers
     */
    async getAllActive(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AllTimeRankedBoxerResponse>> {
        const response = await this.getAllActiveRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAllWithBatchStatus without sending the request
     */
    async getAllWithBatchStatusRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/all-time-ranked-boxers/with-isActive`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns all ranked boxers and indicates whether their batch is active.
     * Get all ranked boxers with isActive status
     */
    async getAllWithBatchStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AllTimeRankedBoxerWithBatchStatusResponse>>> {
        const requestOptions = await this.getAllWithBatchStatusRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AllTimeRankedBoxerWithBatchStatusResponseFromJSON));
    }

    /**
     * Returns all ranked boxers and indicates whether their batch is active.
     * Get all ranked boxers with isActive status
     */
    async getAllWithBatchStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AllTimeRankedBoxerWithBatchStatusResponse>> {
        const response = await this.getAllWithBatchStatusRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getByBatchId without sending the request
     */
    async getByBatchIdRequestOpts(requestParameters: GetByBatchIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['batchId'] == null) {
            throw new runtime.RequiredError(
                'batchId',
                'Required parameter "batchId" was null or undefined when calling getByBatchId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/all-time-ranked-boxers/batch/{batchId}`;
        urlPath = urlPath.replace(`{${"batchId"}}`, encodeURIComponent(String(requestParameters['batchId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns all ranked boxers from a specific generation batch.
     * Get ranked boxers by batch ID
     */
    async getByBatchIdRaw(requestParameters: GetByBatchIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AllTimeRankedBoxerResponse>>> {
        const requestOptions = await this.getByBatchIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AllTimeRankedBoxerResponseFromJSON));
    }

    /**
     * Returns all ranked boxers from a specific generation batch.
     * Get ranked boxers by batch ID
     */
    async getByBatchId(requestParameters: GetByBatchIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AllTimeRankedBoxerResponse>> {
        const response = await this.getByBatchIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getById without sending the request
     */
    async getByIdRequestOpts(requestParameters: GetByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/all-time-ranked-boxers/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns one all-time ranked boxer record by ID.
     * Get ranked boxer by ID
     */
    async getByIdRaw(requestParameters: GetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AllTimeRankedBoxerResponse>> {
        const requestOptions = await this.getByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AllTimeRankedBoxerResponseFromJSON(jsonValue));
    }

    /**
     * Returns one all-time ranked boxer record by ID.
     * Get ranked boxer by ID
     */
    async getById(requestParameters: GetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AllTimeRankedBoxerResponse> {
        const response = await this.getByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getByWeightClassId1 without sending the request
     */
    async getByWeightClassId1RequestOpts(requestParameters: GetByWeightClassId1Request): Promise<runtime.RequestOpts> {
        if (requestParameters['weightClassId'] == null) {
            throw new runtime.RequiredError(
                'weightClassId',
                'Required parameter "weightClassId" was null or undefined when calling getByWeightClassId1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/all-time-ranked-boxers/weight-class/{weightClassId}`;
        urlPath = urlPath.replace(`{${"weightClassId"}}`, encodeURIComponent(String(requestParameters['weightClassId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns ranked boxer records for a weight class.
     * Get ranked boxers by weight class ID
     */
    async getByWeightClassId1Raw(requestParameters: GetByWeightClassId1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AllTimeRankedBoxerResponse>>> {
        const requestOptions = await this.getByWeightClassId1RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AllTimeRankedBoxerResponseFromJSON));
    }

    /**
     * Returns ranked boxer records for a weight class.
     * Get ranked boxers by weight class ID
     */
    async getByWeightClassId1(requestParameters: GetByWeightClassId1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AllTimeRankedBoxerResponse>> {
        const response = await this.getByWeightClassId1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for update without sending the request
     */
    async updateRequestOpts(requestParameters: UpdateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling update().'
            );
        }

        if (requestParameters['allTimeRankedBoxerUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'allTimeRankedBoxerUpdateRequest',
                'Required parameter "allTimeRankedBoxerUpdateRequest" was null or undefined when calling update().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/all-time-ranked-boxers/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: AllTimeRankedBoxerUpdateRequestToJSON(requestParameters['allTimeRankedBoxerUpdateRequest']),
        };
    }

    /**
     * Updates one all-time ranked boxer record. Requires a valid Bearer JWT.
     * Update ranked boxer
     */
    async updateRaw(requestParameters: UpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AllTimeRankedBoxerResponse>> {
        const requestOptions = await this.updateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AllTimeRankedBoxerResponseFromJSON(jsonValue));
    }

    /**
     * Updates one all-time ranked boxer record. Requires a valid Bearer JWT.
     * Update ranked boxer
     */
    async update(requestParameters: UpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AllTimeRankedBoxerResponse> {
        const response = await this.updateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
