/* tslint:disable */
/* eslint-disable */
/**
 * Nexus Boxing API
 * REST API for authentication, all time ranked boxers, perfect boxer generation, updating category weights, making predictions, managing prediction histories, and weight classes.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AdminResponse,
  ApiErrorResponse,
  AuthRequest,
  AuthResponse,
} from '../models';
import {
    AdminResponseFromJSON,
    AdminResponseToJSON,
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    AuthRequestFromJSON,
    AuthRequestToJSON,
    AuthResponseFromJSON,
    AuthResponseToJSON,
} from '../models';

export interface LoginRequest {
    authRequest: AuthRequest;
}

/**
 * 
 */
export class AuthenticationApi extends runtime.BaseAPI {

    /**
     * Creates request options for getCurrentAdmin without sending the request
     */
    async getCurrentAdminRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/auth/me`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns details of the currently authenticated admin using the JWT token.
     * Get current authenticated admin
     */
    async getCurrentAdminRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminResponse>> {
        const requestOptions = await this.getCurrentAdminRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminResponseFromJSON(jsonValue));
    }

    /**
     * Returns details of the currently authenticated admin using the JWT token.
     * Get current authenticated admin
     */
    async getCurrentAdmin(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminResponse> {
        const response = await this.getCurrentAdminRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for login without sending the request
     */
    async loginRequestOpts(requestParameters: LoginRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['authRequest'] == null) {
            throw new runtime.RequiredError(
                'authRequest',
                'Required parameter "authRequest" was null or undefined when calling login().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/auth/login`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthRequestToJSON(requestParameters['authRequest']),
        };
    }

    /**
     * Authenticates an admin and returns a JWT access token. This endpoint is public.
     * Login
     */
    async loginRaw(requestParameters: LoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthResponse>> {
        const requestOptions = await this.loginRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthResponseFromJSON(jsonValue));
    }

    /**
     * Authenticates an admin and returns a JWT access token. This endpoint is public.
     * Login
     */
    async login(requestParameters: LoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthResponse> {
        const response = await this.loginRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
