/* tslint:disable */
/* eslint-disable */
/**
 * Nexus Boxing API
 * REST API for authentication, all time ranked boxers, perfect boxer generation, updating category weights, making predictions, managing prediction histories, and weight classes.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiErrorResponse,
  CategoryWeightResponse,
  CategoryWeightUpdateRequest,
} from '../models/index';
import {
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    CategoryWeightResponseFromJSON,
    CategoryWeightResponseToJSON,
    CategoryWeightUpdateRequestFromJSON,
    CategoryWeightUpdateRequestToJSON,
} from '../models/index';

export interface GetByWeightClassIdRequest {
    weightClassId: number;
}

export interface UpdateByWeightClassIdRequest {
    weightClassId: number;
    categoryWeightUpdateRequest: CategoryWeightUpdateRequest;
}

/**
 * 
 */
export class CategoryWeightsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getAll without sending the request
     */
    async getAllRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/category-weights`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns all category weight records across all weight classes. Requires a valid Bearer JWT.
     * Get all category weights
     */
    async getAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CategoryWeightResponse>>> {
        const requestOptions = await this.getAllRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CategoryWeightResponseFromJSON));
    }

    /**
     * Returns all category weight records across all weight classes. Requires a valid Bearer JWT.
     * Get all category weights
     */
    async getAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CategoryWeightResponse>> {
        const response = await this.getAllRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getByWeightClassId without sending the request
     */
    async getByWeightClassIdRequestOpts(requestParameters: GetByWeightClassIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['weightClassId'] == null) {
            throw new runtime.RequiredError(
                'weightClassId',
                'Required parameter "weightClassId" was null or undefined when calling getByWeightClassId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/category-weights/weight-class/{weightClassId}`;
        urlPath = urlPath.replace(`{${"weightClassId"}}`, encodeURIComponent(String(requestParameters['weightClassId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the category weights for a specific weight class. Requires a valid Bearer JWT.
     * Get category weights by weight class ID
     */
    async getByWeightClassIdRaw(requestParameters: GetByWeightClassIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CategoryWeightResponse>> {
        const requestOptions = await this.getByWeightClassIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CategoryWeightResponseFromJSON(jsonValue));
    }

    /**
     * Returns the category weights for a specific weight class. Requires a valid Bearer JWT.
     * Get category weights by weight class ID
     */
    async getByWeightClassId(requestParameters: GetByWeightClassIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CategoryWeightResponse> {
        const response = await this.getByWeightClassIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateByWeightClassId without sending the request
     */
    async updateByWeightClassIdRequestOpts(requestParameters: UpdateByWeightClassIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['weightClassId'] == null) {
            throw new runtime.RequiredError(
                'weightClassId',
                'Required parameter "weightClassId" was null or undefined when calling updateByWeightClassId().'
            );
        }

        if (requestParameters['categoryWeightUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'categoryWeightUpdateRequest',
                'Required parameter "categoryWeightUpdateRequest" was null or undefined when calling updateByWeightClassId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/category-weights/weight-class/{weightClassId}`;
        urlPath = urlPath.replace(`{${"weightClassId"}}`, encodeURIComponent(String(requestParameters['weightClassId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CategoryWeightUpdateRequestToJSON(requestParameters['categoryWeightUpdateRequest']),
        };
    }

    /**
     * Updates the category weights for a specific weight class. The weights must add up to 1.0. Requires a valid Bearer JWT.
     * Update category weights by weight class ID
     */
    async updateByWeightClassIdRaw(requestParameters: UpdateByWeightClassIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CategoryWeightResponse>> {
        const requestOptions = await this.updateByWeightClassIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CategoryWeightResponseFromJSON(jsonValue));
    }

    /**
     * Updates the category weights for a specific weight class. The weights must add up to 1.0. Requires a valid Bearer JWT.
     * Update category weights by weight class ID
     */
    async updateByWeightClassId(requestParameters: UpdateByWeightClassIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CategoryWeightResponse> {
        const response = await this.updateByWeightClassIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
