/* tslint:disable */
/* eslint-disable */
/**
 * Nexus Boxing API
 * REST API for authentication, all time ranked boxers, perfect boxer generation, updating category weights, making predictions, managing prediction histories, and weight classes.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiErrorResponse,
  PredictMatchRequest,
  PredictionResponse,
} from '../models/index';
import {
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    PredictMatchRequestFromJSON,
    PredictMatchRequestToJSON,
    PredictionResponseFromJSON,
    PredictionResponseToJSON,
} from '../models/index';

export interface PredictRequest {
    predictMatchRequest: PredictMatchRequest;
}

/**
 * 
 */
export class MatchPredictionApi extends runtime.BaseAPI {

    /**
     * Creates request options for predict without sending the request
     */
    async predictRequestOpts(requestParameters: PredictRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['predictMatchRequest'] == null) {
            throw new runtime.RequiredError(
                'predictMatchRequest',
                'Required parameter "predictMatchRequest" was null or undefined when calling predict().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/predictions`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PredictMatchRequestToJSON(requestParameters['predictMatchRequest']),
        };
    }

    /**
     * Predicts the outcome of a boxing match between two fighters.  The system: - Normalizes all attributes using Min-Max normalization - Applies category-based weighting - Calculates each fighter\'s closeness to the Perfect Boxer - Converts closeness into win probabilities - Determines a predicted winner (or draw if equal)  The result includes probabilities, closeness scores, category breakdowns, and an AI-generated explanation. 
     * Predict match outcome
     */
    async predictRaw(requestParameters: PredictRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PredictionResponse>> {
        const requestOptions = await this.predictRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PredictionResponseFromJSON(jsonValue));
    }

    /**
     * Predicts the outcome of a boxing match between two fighters.  The system: - Normalizes all attributes using Min-Max normalization - Applies category-based weighting - Calculates each fighter\'s closeness to the Perfect Boxer - Converts closeness into win probabilities - Determines a predicted winner (or draw if equal)  The result includes probabilities, closeness scores, category breakdowns, and an AI-generated explanation. 
     * Predict match outcome
     */
    async predict(requestParameters: PredictRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PredictionResponse> {
        const response = await this.predictRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
