/* tslint:disable */
/* eslint-disable */
/**
 * Nexus Boxing API
 * REST API for authentication, all time ranked boxers, perfect boxer generation, updating category weights, making predictions, managing prediction histories, and weight classes.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiErrorResponse,
  PerfectBoxerBatchStatusResponse,
  PerfectBoxerGenerationRequest,
  PerfectBoxerGenerationStartedResponse,
  PerfectBoxerResponse,
} from '../models';
import {
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    PerfectBoxerBatchStatusResponseFromJSON,
    PerfectBoxerBatchStatusResponseToJSON,
    PerfectBoxerGenerationRequestFromJSON,
    PerfectBoxerGenerationRequestToJSON,
    PerfectBoxerGenerationStartedResponseFromJSON,
    PerfectBoxerGenerationStartedResponseToJSON,
    PerfectBoxerResponseFromJSON,
    PerfectBoxerResponseToJSON,
} from '../models';

export interface GenerateRequest {
    perfectBoxerGenerationRequest: PerfectBoxerGenerationRequest;
}

export interface GetActiveByWeightClassIdRequest {
    weightClassId: number;
}

export interface GetBatchStatusRequest {
    batchId: number;
}

export interface GetById1Request {
    id: number;
}

export interface RecalculateByWeightClassRequest {
    weightClassId: number;
}

/**
 * 
 */
export class PerfectBoxersApi extends runtime.BaseAPI {

    /**
     * Creates request options for generate without sending the request
     */
    async generateRequestOpts(requestParameters: GenerateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['perfectBoxerGenerationRequest'] == null) {
            throw new runtime.RequiredError(
                'perfectBoxerGenerationRequest',
                'Required parameter "perfectBoxerGenerationRequest" was null or undefined when calling generate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/perfect-boxers/generate`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PerfectBoxerGenerationRequestToJSON(requestParameters['perfectBoxerGenerationRequest']),
        };
    }

    /**
     * Starts asynchronous perfect boxer generation for a weight class. Requires a valid Bearer JWT.
     * Start perfect boxer generation
     */
    async generateRaw(requestParameters: GenerateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PerfectBoxerGenerationStartedResponse>> {
        const requestOptions = await this.generateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PerfectBoxerGenerationStartedResponseFromJSON(jsonValue));
    }

    /**
     * Starts asynchronous perfect boxer generation for a weight class. Requires a valid Bearer JWT.
     * Start perfect boxer generation
     */
    async generate(requestParameters: GenerateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PerfectBoxerGenerationStartedResponse> {
        const response = await this.generateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getActiveByWeightClassId without sending the request
     */
    async getActiveByWeightClassIdRequestOpts(requestParameters: GetActiveByWeightClassIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['weightClassId'] == null) {
            throw new runtime.RequiredError(
                'weightClassId',
                'Required parameter "weightClassId" was null or undefined when calling getActiveByWeightClassId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/perfect-boxers/active/weight-class/{weightClassId}`;
        urlPath = urlPath.replace(`{${"weightClassId"}}`, encodeURIComponent(String(requestParameters['weightClassId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the currently active perfect boxer for a specific weight class
     * Get active perfect boxer by weight class
     */
    async getActiveByWeightClassIdRaw(requestParameters: GetActiveByWeightClassIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PerfectBoxerResponse>> {
        const requestOptions = await this.getActiveByWeightClassIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PerfectBoxerResponseFromJSON(jsonValue));
    }

    /**
     * Returns the currently active perfect boxer for a specific weight class
     * Get active perfect boxer by weight class
     */
    async getActiveByWeightClassId(requestParameters: GetActiveByWeightClassIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PerfectBoxerResponse> {
        const response = await this.getActiveByWeightClassIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAllActivePerfectBoxers without sending the request
     */
    async getAllActivePerfectBoxersRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/perfect-boxers/active`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns all active perfect boxer records across weight classes
     * Get all active perfect boxers
     */
    async getAllActivePerfectBoxersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PerfectBoxerResponse>>> {
        const requestOptions = await this.getAllActivePerfectBoxersRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PerfectBoxerResponseFromJSON));
    }

    /**
     * Returns all active perfect boxer records across weight classes
     * Get all active perfect boxers
     */
    async getAllActivePerfectBoxers(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PerfectBoxerResponse>> {
        const response = await this.getAllActivePerfectBoxersRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getBatchStatus without sending the request
     */
    async getBatchStatusRequestOpts(requestParameters: GetBatchStatusRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['batchId'] == null) {
            throw new runtime.RequiredError(
                'batchId',
                'Required parameter "batchId" was null or undefined when calling getBatchStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/perfect-boxers/batches/{batchId}/status`;
        urlPath = urlPath.replace(`{${"batchId"}}`, encodeURIComponent(String(requestParameters['batchId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the current status of a perfect boxer generation batch. Requires a valid Bearer JWT.
     * Get batch status
     */
    async getBatchStatusRaw(requestParameters: GetBatchStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PerfectBoxerBatchStatusResponse>> {
        const requestOptions = await this.getBatchStatusRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PerfectBoxerBatchStatusResponseFromJSON(jsonValue));
    }

    /**
     * Returns the current status of a perfect boxer generation batch. Requires a valid Bearer JWT.
     * Get batch status
     */
    async getBatchStatus(requestParameters: GetBatchStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PerfectBoxerBatchStatusResponse> {
        const response = await this.getBatchStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getById1 without sending the request
     */
    async getById1RequestOpts(requestParameters: GetById1Request): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getById1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/perfect-boxers/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a fully detailed perfect boxer record including all attributes
     * Get perfect boxer by ID
     */
    async getById1Raw(requestParameters: GetById1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PerfectBoxerResponse>> {
        const requestOptions = await this.getById1RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PerfectBoxerResponseFromJSON(jsonValue));
    }

    /**
     * Returns a fully detailed perfect boxer record including all attributes
     * Get perfect boxer by ID
     */
    async getById1(requestParameters: GetById1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PerfectBoxerResponse> {
        const response = await this.getById1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for recalculateByWeightClass without sending the request
     */
    async recalculateByWeightClassRequestOpts(requestParameters: RecalculateByWeightClassRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['weightClassId'] == null) {
            throw new runtime.RequiredError(
                'weightClassId',
                'Required parameter "weightClassId" was null or undefined when calling recalculateByWeightClass().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/perfect-boxers/recalculate/weight-class/{weightClassId}`;
        urlPath = urlPath.replace(`{${"weightClassId"}}`, encodeURIComponent(String(requestParameters['weightClassId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Recalculates the perfect boxer using the active batch for a weight class. Requires a valid Bearer JWT.
     * Regenerate active perfect boxer by weight class
     */
    async recalculateByWeightClassRaw(requestParameters: RecalculateByWeightClassRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PerfectBoxerResponse>> {
        const requestOptions = await this.recalculateByWeightClassRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PerfectBoxerResponseFromJSON(jsonValue));
    }

    /**
     * Recalculates the perfect boxer using the active batch for a weight class. Requires a valid Bearer JWT.
     * Regenerate active perfect boxer by weight class
     */
    async recalculateByWeightClass(requestParameters: RecalculateByWeightClassRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PerfectBoxerResponse> {
        const response = await this.recalculateByWeightClassRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
