/* tslint:disable */
/* eslint-disable */
/**
 * Nexus Boxing API
 * REST API for authentication, all time ranked boxers, perfect boxer generation, updating category weights, making predictions, managing prediction histories, and weight classes.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiErrorResponse,
  PredictionHistoryResponse,
  PredictionResultUpdateRequest,
} from '../models/index';
import {
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    PredictionHistoryResponseFromJSON,
    PredictionHistoryResponseToJSON,
    PredictionResultUpdateRequestFromJSON,
    PredictionResultUpdateRequestToJSON,
} from '../models/index';

export interface DeletePredictionHistoryRequest {
    id: number;
}

export interface GetPredictionHistoryByIdRequest {
    id: number;
}

export interface UpdatePredictionHistoryRequest {
    id: number;
    predictionResultUpdateRequest: PredictionResultUpdateRequest;
}

/**
 * 
 */
export class PredictionHistoryApi extends runtime.BaseAPI {

    /**
     * Creates request options for deletePredictionHistory without sending the request
     */
    async deletePredictionHistoryRequestOpts(requestParameters: DeletePredictionHistoryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deletePredictionHistory().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/prediction-history/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Deletes a saved prediction history record by ID. Requires a valid Bearer JWT.
     * Delete prediction history
     */
    async deletePredictionHistoryRaw(requestParameters: DeletePredictionHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deletePredictionHistoryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes a saved prediction history record by ID. Requires a valid Bearer JWT.
     * Delete prediction history
     */
    async deletePredictionHistory(requestParameters: DeletePredictionHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deletePredictionHistoryRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getPredictionHistories without sending the request
     */
    async getPredictionHistoriesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/prediction-history`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns all saved prediction history records.
     * Get all prediction history
     */
    async getPredictionHistoriesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PredictionHistoryResponse>>> {
        const requestOptions = await this.getPredictionHistoriesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PredictionHistoryResponseFromJSON));
    }

    /**
     * Returns all saved prediction history records.
     * Get all prediction history
     */
    async getPredictionHistories(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PredictionHistoryResponse>> {
        const response = await this.getPredictionHistoriesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPredictionHistoryById without sending the request
     */
    async getPredictionHistoryByIdRequestOpts(requestParameters: GetPredictionHistoryByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getPredictionHistoryById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/prediction-history/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns one saved prediction history record by prediction ID.
     * Get prediction history by ID
     */
    async getPredictionHistoryByIdRaw(requestParameters: GetPredictionHistoryByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PredictionHistoryResponse>> {
        const requestOptions = await this.getPredictionHistoryByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PredictionHistoryResponseFromJSON(jsonValue));
    }

    /**
     * Returns one saved prediction history record by prediction ID.
     * Get prediction history by ID
     */
    async getPredictionHistoryById(requestParameters: GetPredictionHistoryByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PredictionHistoryResponse> {
        const response = await this.getPredictionHistoryByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updatePredictionHistory without sending the request
     */
    async updatePredictionHistoryRequestOpts(requestParameters: UpdatePredictionHistoryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updatePredictionHistory().'
            );
        }

        if (requestParameters['predictionResultUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'predictionResultUpdateRequest',
                'Required parameter "predictionResultUpdateRequest" was null or undefined when calling updatePredictionHistory().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/prediction-history/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PredictionResultUpdateRequestToJSON(requestParameters['predictionResultUpdateRequest']),
        };
    }

    /**
     * Updates an existing saved prediction history record. Requires a valid Bearer JWT.
     * Update prediction history
     */
    async updatePredictionHistoryRaw(requestParameters: UpdatePredictionHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PredictionHistoryResponse>> {
        const requestOptions = await this.updatePredictionHistoryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PredictionHistoryResponseFromJSON(jsonValue));
    }

    /**
     * Updates an existing saved prediction history record. Requires a valid Bearer JWT.
     * Update prediction history
     */
    async updatePredictionHistory(requestParameters: UpdatePredictionHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PredictionHistoryResponse> {
        const response = await this.updatePredictionHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
