/* tslint:disable */
/* eslint-disable */
/**
 * Nexus Boxing API
 * REST API for authentication, all time ranked boxers, perfect boxer generation, updating category weights, making predictions, managing prediction histories, and weight classes.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiErrorResponse,
  WeightClassResponse,
} from '../models/index';
import {
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    WeightClassResponseFromJSON,
    WeightClassResponseToJSON,
} from '../models/index';

export interface GetWeightClassByIdRequest {
    id: number;
}

export interface GetWeightClassByNameRequest {
    className: string;
}

/**
 * 
 */
export class WeightClassesApi extends runtime.BaseAPI {

    /**
     * Creates request options for getWeightClassById without sending the request
     */
    async getWeightClassByIdRequestOpts(requestParameters: GetWeightClassByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getWeightClassById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/weight-classes/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a single weight class by its ID. This endpoint is public.
     * Get weight class by ID
     */
    async getWeightClassByIdRaw(requestParameters: GetWeightClassByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WeightClassResponse>> {
        const requestOptions = await this.getWeightClassByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WeightClassResponseFromJSON(jsonValue));
    }

    /**
     * Returns a single weight class by its ID. This endpoint is public.
     * Get weight class by ID
     */
    async getWeightClassById(requestParameters: GetWeightClassByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WeightClassResponse> {
        const response = await this.getWeightClassByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getWeightClassByName without sending the request
     */
    async getWeightClassByNameRequestOpts(requestParameters: GetWeightClassByNameRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['className'] == null) {
            throw new runtime.RequiredError(
                'className',
                'Required parameter "className" was null or undefined when calling getWeightClassByName().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/weight-classes/name/{className}`;
        urlPath = urlPath.replace(`{${"className"}}`, encodeURIComponent(String(requestParameters['className'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a single weight class by its class name. This endpoint is public.
     * Get weight class by name
     */
    async getWeightClassByNameRaw(requestParameters: GetWeightClassByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WeightClassResponse>> {
        const requestOptions = await this.getWeightClassByNameRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WeightClassResponseFromJSON(jsonValue));
    }

    /**
     * Returns a single weight class by its class name. This endpoint is public.
     * Get weight class by name
     */
    async getWeightClassByName(requestParameters: GetWeightClassByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WeightClassResponse> {
        const response = await this.getWeightClassByNameRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getWeightClasses without sending the request
     */
    async getWeightClassesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/weight-classes`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns all boxing weight classes. This endpoint is public.
     * Get all weight classes
     */
    async getWeightClassesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WeightClassResponse>>> {
        const requestOptions = await this.getWeightClassesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WeightClassResponseFromJSON));
    }

    /**
     * Returns all boxing weight classes. This endpoint is public.
     * Get all weight classes
     */
    async getWeightClasses(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WeightClassResponse>> {
        const response = await this.getWeightClassesRaw(initOverrides);
        return await response.value();
    }

}
