/* tslint:disable */
/* eslint-disable */
/**
 * Nexus Boxing API
 * REST API for authentication, all time ranked boxers, perfect boxer generation, updating category weights, making predictions, managing prediction histories, and weight classes.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response containing admin account details
 * @export
 * @interface AdminResponse
 */
export interface AdminResponse {
    /**
     * Unique admin ID
     * @type {number}
     * @memberof AdminResponse
     */
    adminId?: number;
    /**
     * Admin username
     * @type {string}
     * @memberof AdminResponse
     */
    username?: string;
    /**
     * Date and time when the admin account was created
     * @type {Date}
     * @memberof AdminResponse
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the AdminResponse interface.
 */
export function instanceOfAdminResponse(value: object): value is AdminResponse {
    return true;
}

export function AdminResponseFromJSON(json: any): AdminResponse {
    return AdminResponseFromJSONTyped(json, false);
}

export function AdminResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'adminId': json['adminId'] == null ? undefined : json['adminId'],
        'username': json['username'] == null ? undefined : json['username'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function AdminResponseToJSON(json: any): AdminResponse {
    return AdminResponseToJSONTyped(json, false);
}

export function AdminResponseToJSONTyped(value?: AdminResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'adminId': value['adminId'],
        'username': value['username'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

