/* tslint:disable */
/* eslint-disable */
/**
 * Nexus Boxing API
 * REST API for authentication, all time ranked boxers, perfect boxer generation, updating category weights, making predictions, managing prediction histories, and weight classes.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AllTimeRankedBoxerResponse } from './AllTimeRankedBoxerResponse';
import {
    AllTimeRankedBoxerResponseFromJSON,
    AllTimeRankedBoxerResponseFromJSONTyped,
    AllTimeRankedBoxerResponseToJSON,
    AllTimeRankedBoxerResponseToJSONTyped,
} from './AllTimeRankedBoxerResponse';

/**
 * 
 * @export
 * @interface AllTimeRankedBoxerWithBatchStatusResponse
 */
export interface AllTimeRankedBoxerWithBatchStatusResponse {
    /**
     * 
     * @type {AllTimeRankedBoxerResponse}
     * @memberof AllTimeRankedBoxerWithBatchStatusResponse
     */
    boxer?: AllTimeRankedBoxerResponse;
    /**
     * 
     * @type {boolean}
     * @memberof AllTimeRankedBoxerWithBatchStatusResponse
     */
    isActive?: boolean;
}

/**
 * Check if a given object implements the AllTimeRankedBoxerWithBatchStatusResponse interface.
 */
export function instanceOfAllTimeRankedBoxerWithBatchStatusResponse(value: object): value is AllTimeRankedBoxerWithBatchStatusResponse {
    return true;
}

export function AllTimeRankedBoxerWithBatchStatusResponseFromJSON(json: any): AllTimeRankedBoxerWithBatchStatusResponse {
    return AllTimeRankedBoxerWithBatchStatusResponseFromJSONTyped(json, false);
}

export function AllTimeRankedBoxerWithBatchStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllTimeRankedBoxerWithBatchStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'boxer': json['boxer'] == null ? undefined : AllTimeRankedBoxerResponseFromJSON(json['boxer']),
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
    };
}

export function AllTimeRankedBoxerWithBatchStatusResponseToJSON(json: any): AllTimeRankedBoxerWithBatchStatusResponse {
    return AllTimeRankedBoxerWithBatchStatusResponseToJSONTyped(json, false);
}

export function AllTimeRankedBoxerWithBatchStatusResponseToJSONTyped(value?: AllTimeRankedBoxerWithBatchStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'boxer': AllTimeRankedBoxerResponseToJSON(value['boxer']),
        'isActive': value['isActive'],
    };
}

