/* tslint:disable */
/* eslint-disable */
/**
 * Nexus Boxing API
 * REST API for authentication, all time ranked boxers, perfect boxer generation, updating category weights, making predictions, managing prediction histories, and weight classes.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response containing a ranked all-time boxer profile used in a generation batch
 * @export
 * @interface AllTimeRankedBoxerResponse
 */
export interface AllTimeRankedBoxerResponse {
    /**
     * Unique ID of the ranked boxer record
     * @type {number}
     * @memberof AllTimeRankedBoxerResponse
     */
    rankedBoxerId?: number;
    /**
     * Batch ID this ranked boxer belongs to
     * @type {number}
     * @memberof AllTimeRankedBoxerResponse
     */
    batchId?: number;
    /**
     * Weight class ID for this ranked boxer record
     * @type {number}
     * @memberof AllTimeRankedBoxerResponse
     */
    weightClassId?: number;
    /**
     * Name of the boxer
     * @type {string}
     * @memberof AllTimeRankedBoxerResponse
     */
    boxerName?: string;
    /**
     * Ranking position of the boxer within the batch
     * @type {number}
     * @memberof AllTimeRankedBoxerResponse
     */
    rankingPosition?: number;
    /**
     * Height of the boxer in centimeters
     * @type {number}
     * @memberof AllTimeRankedBoxerResponse
     */
    heightCm?: number;
    /**
     * Reach of the boxer in centimeters
     * @type {number}
     * @memberof AllTimeRankedBoxerResponse
     */
    reachCm?: number;
    /**
     * Score representing how naturally aligned the boxer is with the weight class
     * @type {number}
     * @memberof AllTimeRankedBoxerResponse
     */
    weightClassAlignment?: number;
    /**
     * Score representing hand speed
     * @type {number}
     * @memberof AllTimeRankedBoxerResponse
     */
    handSpeed?: number;
    /**
     * Score representing foot speed
     * @type {number}
     * @memberof AllTimeRankedBoxerResponse
     */
    footSpeed?: number;
    /**
     * Score representing strength
     * @type {number}
     * @memberof AllTimeRankedBoxerResponse
     */
    strength?: number;
    /**
     * Score representing endurance
     * @type {number}
     * @memberof AllTimeRankedBoxerResponse
     */
    endurance?: number;
    /**
     * Score representing reaction time
     * @type {number}
     * @memberof AllTimeRankedBoxerResponse
     */
    reactionTime?: number;
    /**
     * Score representing punch accuracy
     * @type {number}
     * @memberof AllTimeRankedBoxerResponse
     */
    punchAccuracy?: number;
    /**
     * Score representing punch variety
     * @type {number}
     * @memberof AllTimeRankedBoxerResponse
     */
    punchVariety?: number;
    /**
     * Score representing defensive guard efficiency
     * @type {number}
     * @memberof AllTimeRankedBoxerResponse
     */
    defensiveGuardEfficiency?: number;
    /**
     * Score representing head movement
     * @type {number}
     * @memberof AllTimeRankedBoxerResponse
     */
    headMovement?: number;
    /**
     * Score representing footwork technique
     * @type {number}
     * @memberof AllTimeRankedBoxerResponse
     */
    footworkTechnique?: number;
    /**
     * Score representing counterpunching ability
     * @type {number}
     * @memberof AllTimeRankedBoxerResponse
     */
    counterpunchingAbility?: number;
    /**
     * Score representing combination efficiency
     * @type {number}
     * @memberof AllTimeRankedBoxerResponse
     */
    combinationEfficiency?: number;
    /**
     * Score representing ring IQ
     * @type {number}
     * @memberof AllTimeRankedBoxerResponse
     */
    ringIq?: number;
    /**
     * Score representing adaptability during a fight
     * @type {number}
     * @memberof AllTimeRankedBoxerResponse
     */
    adaptabilityMidFight?: number;
    /**
     * Score representing distance control
     * @type {number}
     * @memberof AllTimeRankedBoxerResponse
     */
    distanceControl?: number;
    /**
     * Score representing tempo control
     * @type {number}
     * @memberof AllTimeRankedBoxerResponse
     */
    tempoControl?: number;
    /**
     * Score representing ability to recognize opponent patterns
     * @type {number}
     * @memberof AllTimeRankedBoxerResponse
     */
    opponentPatternRecognition?: number;
    /**
     * Score representing fight planning discipline
     * @type {number}
     * @memberof AllTimeRankedBoxerResponse
     */
    fightPlanningDiscipline?: number;
    /**
     * Score representing composure under pressure
     * @type {number}
     * @memberof AllTimeRankedBoxerResponse
     */
    composureUnderPressure?: number;
    /**
     * Score representing aggression control
     * @type {number}
     * @memberof AllTimeRankedBoxerResponse
     */
    aggressionControl?: number;
    /**
     * Score representing mental toughness
     * @type {number}
     * @memberof AllTimeRankedBoxerResponse
     */
    mentalToughness?: number;
    /**
     * Score representing focus consistency
     * @type {number}
     * @memberof AllTimeRankedBoxerResponse
     */
    focusConsistency?: number;
    /**
     * Score representing resilience after knockdown
     * @type {number}
     * @memberof AllTimeRankedBoxerResponse
     */
    resilienceAfterKnockdown?: number;
    /**
     * Career win ratio expressed as a decimal
     * @type {number}
     * @memberof AllTimeRankedBoxerResponse
     */
    winRatio?: number;
    /**
     * Career knockout ratio expressed as a decimal
     * @type {number}
     * @memberof AllTimeRankedBoxerResponse
     */
    knockoutRatio?: number;
    /**
     * Score representing title fight experience
     * @type {number}
     * @memberof AllTimeRankedBoxerResponse
     */
    titleFightExperience?: number;
    /**
     * Score representing strength of opposition faced
     * @type {number}
     * @memberof AllTimeRankedBoxerResponse
     */
    strengthOfOpposition?: number;
    /**
     * Score representing recent fight activity
     * @type {number}
     * @memberof AllTimeRankedBoxerResponse
     */
    recentFightActivity?: number;
    /**
     * Score representing consistency of performance
     * @type {number}
     * @memberof AllTimeRankedBoxerResponse
     */
    performanceConsistency?: number;
    /**
     * Optional note describing source confidence or supporting context
     * @type {string}
     * @memberof AllTimeRankedBoxerResponse
     */
    sourceNote?: string;
    /**
     * Date and time when this ranked boxer record was generated
     * @type {Date}
     * @memberof AllTimeRankedBoxerResponse
     */
    generatedAt?: Date;
}

/**
 * Check if a given object implements the AllTimeRankedBoxerResponse interface.
 */
export function instanceOfAllTimeRankedBoxerResponse(value: object): value is AllTimeRankedBoxerResponse {
    return true;
}

export function AllTimeRankedBoxerResponseFromJSON(json: any): AllTimeRankedBoxerResponse {
    return AllTimeRankedBoxerResponseFromJSONTyped(json, false);
}

export function AllTimeRankedBoxerResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllTimeRankedBoxerResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'rankedBoxerId': json['rankedBoxerId'] == null ? undefined : json['rankedBoxerId'],
        'batchId': json['batchId'] == null ? undefined : json['batchId'],
        'weightClassId': json['weightClassId'] == null ? undefined : json['weightClassId'],
        'boxerName': json['boxerName'] == null ? undefined : json['boxerName'],
        'rankingPosition': json['rankingPosition'] == null ? undefined : json['rankingPosition'],
        'heightCm': json['heightCm'] == null ? undefined : json['heightCm'],
        'reachCm': json['reachCm'] == null ? undefined : json['reachCm'],
        'weightClassAlignment': json['weightClassAlignment'] == null ? undefined : json['weightClassAlignment'],
        'handSpeed': json['handSpeed'] == null ? undefined : json['handSpeed'],
        'footSpeed': json['footSpeed'] == null ? undefined : json['footSpeed'],
        'strength': json['strength'] == null ? undefined : json['strength'],
        'endurance': json['endurance'] == null ? undefined : json['endurance'],
        'reactionTime': json['reactionTime'] == null ? undefined : json['reactionTime'],
        'punchAccuracy': json['punchAccuracy'] == null ? undefined : json['punchAccuracy'],
        'punchVariety': json['punchVariety'] == null ? undefined : json['punchVariety'],
        'defensiveGuardEfficiency': json['defensiveGuardEfficiency'] == null ? undefined : json['defensiveGuardEfficiency'],
        'headMovement': json['headMovement'] == null ? undefined : json['headMovement'],
        'footworkTechnique': json['footworkTechnique'] == null ? undefined : json['footworkTechnique'],
        'counterpunchingAbility': json['counterpunchingAbility'] == null ? undefined : json['counterpunchingAbility'],
        'combinationEfficiency': json['combinationEfficiency'] == null ? undefined : json['combinationEfficiency'],
        'ringIq': json['ringIq'] == null ? undefined : json['ringIq'],
        'adaptabilityMidFight': json['adaptabilityMidFight'] == null ? undefined : json['adaptabilityMidFight'],
        'distanceControl': json['distanceControl'] == null ? undefined : json['distanceControl'],
        'tempoControl': json['tempoControl'] == null ? undefined : json['tempoControl'],
        'opponentPatternRecognition': json['opponentPatternRecognition'] == null ? undefined : json['opponentPatternRecognition'],
        'fightPlanningDiscipline': json['fightPlanningDiscipline'] == null ? undefined : json['fightPlanningDiscipline'],
        'composureUnderPressure': json['composureUnderPressure'] == null ? undefined : json['composureUnderPressure'],
        'aggressionControl': json['aggressionControl'] == null ? undefined : json['aggressionControl'],
        'mentalToughness': json['mentalToughness'] == null ? undefined : json['mentalToughness'],
        'focusConsistency': json['focusConsistency'] == null ? undefined : json['focusConsistency'],
        'resilienceAfterKnockdown': json['resilienceAfterKnockdown'] == null ? undefined : json['resilienceAfterKnockdown'],
        'winRatio': json['winRatio'] == null ? undefined : json['winRatio'],
        'knockoutRatio': json['knockoutRatio'] == null ? undefined : json['knockoutRatio'],
        'titleFightExperience': json['titleFightExperience'] == null ? undefined : json['titleFightExperience'],
        'strengthOfOpposition': json['strengthOfOpposition'] == null ? undefined : json['strengthOfOpposition'],
        'recentFightActivity': json['recentFightActivity'] == null ? undefined : json['recentFightActivity'],
        'performanceConsistency': json['performanceConsistency'] == null ? undefined : json['performanceConsistency'],
        'sourceNote': json['sourceNote'] == null ? undefined : json['sourceNote'],
        'generatedAt': json['generatedAt'] == null ? undefined : (new Date(json['generatedAt'])),
    };
}

export function AllTimeRankedBoxerResponseToJSON(json: any): AllTimeRankedBoxerResponse {
    return AllTimeRankedBoxerResponseToJSONTyped(json, false);
}

export function AllTimeRankedBoxerResponseToJSONTyped(value?: AllTimeRankedBoxerResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rankedBoxerId': value['rankedBoxerId'],
        'batchId': value['batchId'],
        'weightClassId': value['weightClassId'],
        'boxerName': value['boxerName'],
        'rankingPosition': value['rankingPosition'],
        'heightCm': value['heightCm'],
        'reachCm': value['reachCm'],
        'weightClassAlignment': value['weightClassAlignment'],
        'handSpeed': value['handSpeed'],
        'footSpeed': value['footSpeed'],
        'strength': value['strength'],
        'endurance': value['endurance'],
        'reactionTime': value['reactionTime'],
        'punchAccuracy': value['punchAccuracy'],
        'punchVariety': value['punchVariety'],
        'defensiveGuardEfficiency': value['defensiveGuardEfficiency'],
        'headMovement': value['headMovement'],
        'footworkTechnique': value['footworkTechnique'],
        'counterpunchingAbility': value['counterpunchingAbility'],
        'combinationEfficiency': value['combinationEfficiency'],
        'ringIq': value['ringIq'],
        'adaptabilityMidFight': value['adaptabilityMidFight'],
        'distanceControl': value['distanceControl'],
        'tempoControl': value['tempoControl'],
        'opponentPatternRecognition': value['opponentPatternRecognition'],
        'fightPlanningDiscipline': value['fightPlanningDiscipline'],
        'composureUnderPressure': value['composureUnderPressure'],
        'aggressionControl': value['aggressionControl'],
        'mentalToughness': value['mentalToughness'],
        'focusConsistency': value['focusConsistency'],
        'resilienceAfterKnockdown': value['resilienceAfterKnockdown'],
        'winRatio': value['winRatio'],
        'knockoutRatio': value['knockoutRatio'],
        'titleFightExperience': value['titleFightExperience'],
        'strengthOfOpposition': value['strengthOfOpposition'],
        'recentFightActivity': value['recentFightActivity'],
        'performanceConsistency': value['performanceConsistency'],
        'sourceNote': value['sourceNote'],
        'generatedAt': value['generatedAt'] == null ? value['generatedAt'] : value['generatedAt'].toISOString(),
    };
}

