/* tslint:disable */
/* eslint-disable */
/**
 * Nexus Boxing API
 * REST API for authentication, all time ranked boxers, perfect boxer generation, updating category weights, making predictions, managing prediction histories, and weight classes.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Standard API error response
 * @export
 * @interface ApiErrorResponse
 */
export interface ApiErrorResponse {
    /**
     * Date and time when the error occurred
     * @type {Date}
     * @memberof ApiErrorResponse
     */
    timestamp?: Date;
    /**
     * HTTP status code
     * @type {number}
     * @memberof ApiErrorResponse
     */
    status?: number;
    /**
     * Short HTTP error label
     * @type {string}
     * @memberof ApiErrorResponse
     */
    error?: string;
    /**
     * Detailed error message
     * @type {string}
     * @memberof ApiErrorResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the ApiErrorResponse interface.
 */
export function instanceOfApiErrorResponse(value: object): value is ApiErrorResponse {
    return true;
}

export function ApiErrorResponseFromJSON(json: any): ApiErrorResponse {
    return ApiErrorResponseFromJSONTyped(json, false);
}

export function ApiErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'status': json['status'] == null ? undefined : json['status'],
        'error': json['error'] == null ? undefined : json['error'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ApiErrorResponseToJSON(json: any): ApiErrorResponse {
    return ApiErrorResponseToJSONTyped(json, false);
}

export function ApiErrorResponseToJSONTyped(value?: ApiErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
        'status': value['status'],
        'error': value['error'],
        'message': value['message'],
    };
}

