/* tslint:disable */
/* eslint-disable */
/**
 * Nexus Boxing API
 * REST API for authentication, all time ranked boxers, perfect boxer generation, updating category weights, making predictions, managing prediction histories, and weight classes.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response returned after successful authentication
 * @export
 * @interface AuthResponse
 */
export interface AuthResponse {
    /**
     * JWT access token
     * @type {string}
     * @memberof AuthResponse
     */
    token?: string;
    /**
     * Token type to be used in the Authorization header
     * @type {string}
     * @memberof AuthResponse
     */
    tokenType?: string;
    /**
     * Authenticated admin username
     * @type {string}
     * @memberof AuthResponse
     */
    username?: string;
}

/**
 * Check if a given object implements the AuthResponse interface.
 */
export function instanceOfAuthResponse(value: object): value is AuthResponse {
    return true;
}

export function AuthResponseFromJSON(json: any): AuthResponse {
    return AuthResponseFromJSONTyped(json, false);
}

export function AuthResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'] == null ? undefined : json['token'],
        'tokenType': json['tokenType'] == null ? undefined : json['tokenType'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function AuthResponseToJSON(json: any): AuthResponse {
    return AuthResponseToJSONTyped(json, false);
}

export function AuthResponseToJSONTyped(value?: AuthResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'tokenType': value['tokenType'],
        'username': value['username'],
    };
}

