/* tslint:disable */
/* eslint-disable */
/**
 * Nexus Boxing API
 * REST API for authentication, all time ranked boxers, perfect boxer generation, updating category weights, making predictions, managing prediction histories, and weight classes.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response returned when the AI cannot confidently identify a boxer profile
 * @export
 * @interface BoxerProfileLookupFailureResponse
 */
export interface BoxerProfileLookupFailureResponse {
    /**
     * Indicates that the boxer profile lookup failed
     * @type {boolean}
     * @memberof BoxerProfileLookupFailureResponse
     */
    boxerFound?: boolean;
    /**
     * Confidence score of the AI in identifying the boxer (0.0 to 1.0)
     * @type {number}
     * @memberof BoxerProfileLookupFailureResponse
     */
    confidence?: number;
    /**
     * Explanation of why the boxer could not be confidently identified
     * @type {string}
     * @memberof BoxerProfileLookupFailureResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the BoxerProfileLookupFailureResponse interface.
 */
export function instanceOfBoxerProfileLookupFailureResponse(value: object): value is BoxerProfileLookupFailureResponse {
    return true;
}

export function BoxerProfileLookupFailureResponseFromJSON(json: any): BoxerProfileLookupFailureResponse {
    return BoxerProfileLookupFailureResponseFromJSONTyped(json, false);
}

export function BoxerProfileLookupFailureResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BoxerProfileLookupFailureResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'boxerFound': json['boxerFound'] == null ? undefined : json['boxerFound'],
        'confidence': json['confidence'] == null ? undefined : json['confidence'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function BoxerProfileLookupFailureResponseToJSON(json: any): BoxerProfileLookupFailureResponse {
    return BoxerProfileLookupFailureResponseToJSONTyped(json, false);
}

export function BoxerProfileLookupFailureResponseToJSONTyped(value?: BoxerProfileLookupFailureResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'boxerFound': value['boxerFound'],
        'confidence': value['confidence'],
        'message': value['message'],
    };
}

