/* tslint:disable */
/* eslint-disable */
/**
 * Nexus Boxing API
 * REST API for authentication, all time ranked boxers, perfect boxer generation, updating category weights, making predictions, managing prediction histories, and weight classes.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BoxerInput
 */
export interface BoxerInput {
    /**
     * 
     * @type {string}
     * @memberof BoxerInput
     */
    boxerName: string;
    /**
     * 
     * @type {number}
     * @memberof BoxerInput
     */
    attributeConfidence: number;
    /**
     * 
     * @type {number}
     * @memberof BoxerInput
     */
    heightCm: number;
    /**
     * 
     * @type {number}
     * @memberof BoxerInput
     */
    reachCm: number;
    /**
     * 
     * @type {number}
     * @memberof BoxerInput
     */
    weightClassAlignment: number;
    /**
     * 
     * @type {number}
     * @memberof BoxerInput
     */
    handSpeed: number;
    /**
     * 
     * @type {number}
     * @memberof BoxerInput
     */
    footSpeed: number;
    /**
     * 
     * @type {number}
     * @memberof BoxerInput
     */
    strength: number;
    /**
     * 
     * @type {number}
     * @memberof BoxerInput
     */
    endurance: number;
    /**
     * 
     * @type {number}
     * @memberof BoxerInput
     */
    reactionTime: number;
    /**
     * 
     * @type {number}
     * @memberof BoxerInput
     */
    punchAccuracy: number;
    /**
     * 
     * @type {number}
     * @memberof BoxerInput
     */
    punchVariety: number;
    /**
     * 
     * @type {number}
     * @memberof BoxerInput
     */
    defensiveGuardEfficiency: number;
    /**
     * 
     * @type {number}
     * @memberof BoxerInput
     */
    headMovement: number;
    /**
     * 
     * @type {number}
     * @memberof BoxerInput
     */
    footworkTechnique: number;
    /**
     * 
     * @type {number}
     * @memberof BoxerInput
     */
    counterpunchingAbility: number;
    /**
     * 
     * @type {number}
     * @memberof BoxerInput
     */
    combinationEfficiency: number;
    /**
     * 
     * @type {number}
     * @memberof BoxerInput
     */
    ringIq: number;
    /**
     * 
     * @type {number}
     * @memberof BoxerInput
     */
    adaptabilityMidFight: number;
    /**
     * 
     * @type {number}
     * @memberof BoxerInput
     */
    distanceControl: number;
    /**
     * 
     * @type {number}
     * @memberof BoxerInput
     */
    tempoControl: number;
    /**
     * 
     * @type {number}
     * @memberof BoxerInput
     */
    opponentPatternRecognition: number;
    /**
     * 
     * @type {number}
     * @memberof BoxerInput
     */
    fightPlanningDiscipline: number;
    /**
     * 
     * @type {number}
     * @memberof BoxerInput
     */
    composureUnderPressure: number;
    /**
     * 
     * @type {number}
     * @memberof BoxerInput
     */
    aggressionControl: number;
    /**
     * 
     * @type {number}
     * @memberof BoxerInput
     */
    mentalToughness: number;
    /**
     * 
     * @type {number}
     * @memberof BoxerInput
     */
    focusConsistency: number;
    /**
     * 
     * @type {number}
     * @memberof BoxerInput
     */
    resilienceAfterKnockdown: number;
    /**
     * 
     * @type {number}
     * @memberof BoxerInput
     */
    winRatio: number;
    /**
     * 
     * @type {number}
     * @memberof BoxerInput
     */
    knockoutRatio: number;
    /**
     * 
     * @type {number}
     * @memberof BoxerInput
     */
    titleFightExperience: number;
    /**
     * 
     * @type {number}
     * @memberof BoxerInput
     */
    strengthOfOpposition: number;
    /**
     * 
     * @type {number}
     * @memberof BoxerInput
     */
    recentFightActivity: number;
    /**
     * 
     * @type {number}
     * @memberof BoxerInput
     */
    performanceConsistency: number;
}

/**
 * Check if a given object implements the BoxerInput interface.
 */
export function instanceOfBoxerInput(value: object): value is BoxerInput {
    if (!('boxerName' in value) || value['boxerName'] === undefined) return false;
    if (!('attributeConfidence' in value) || value['attributeConfidence'] === undefined) return false;
    if (!('heightCm' in value) || value['heightCm'] === undefined) return false;
    if (!('reachCm' in value) || value['reachCm'] === undefined) return false;
    if (!('weightClassAlignment' in value) || value['weightClassAlignment'] === undefined) return false;
    if (!('handSpeed' in value) || value['handSpeed'] === undefined) return false;
    if (!('footSpeed' in value) || value['footSpeed'] === undefined) return false;
    if (!('strength' in value) || value['strength'] === undefined) return false;
    if (!('endurance' in value) || value['endurance'] === undefined) return false;
    if (!('reactionTime' in value) || value['reactionTime'] === undefined) return false;
    if (!('punchAccuracy' in value) || value['punchAccuracy'] === undefined) return false;
    if (!('punchVariety' in value) || value['punchVariety'] === undefined) return false;
    if (!('defensiveGuardEfficiency' in value) || value['defensiveGuardEfficiency'] === undefined) return false;
    if (!('headMovement' in value) || value['headMovement'] === undefined) return false;
    if (!('footworkTechnique' in value) || value['footworkTechnique'] === undefined) return false;
    if (!('counterpunchingAbility' in value) || value['counterpunchingAbility'] === undefined) return false;
    if (!('combinationEfficiency' in value) || value['combinationEfficiency'] === undefined) return false;
    if (!('ringIq' in value) || value['ringIq'] === undefined) return false;
    if (!('adaptabilityMidFight' in value) || value['adaptabilityMidFight'] === undefined) return false;
    if (!('distanceControl' in value) || value['distanceControl'] === undefined) return false;
    if (!('tempoControl' in value) || value['tempoControl'] === undefined) return false;
    if (!('opponentPatternRecognition' in value) || value['opponentPatternRecognition'] === undefined) return false;
    if (!('fightPlanningDiscipline' in value) || value['fightPlanningDiscipline'] === undefined) return false;
    if (!('composureUnderPressure' in value) || value['composureUnderPressure'] === undefined) return false;
    if (!('aggressionControl' in value) || value['aggressionControl'] === undefined) return false;
    if (!('mentalToughness' in value) || value['mentalToughness'] === undefined) return false;
    if (!('focusConsistency' in value) || value['focusConsistency'] === undefined) return false;
    if (!('resilienceAfterKnockdown' in value) || value['resilienceAfterKnockdown'] === undefined) return false;
    if (!('winRatio' in value) || value['winRatio'] === undefined) return false;
    if (!('knockoutRatio' in value) || value['knockoutRatio'] === undefined) return false;
    if (!('titleFightExperience' in value) || value['titleFightExperience'] === undefined) return false;
    if (!('strengthOfOpposition' in value) || value['strengthOfOpposition'] === undefined) return false;
    if (!('recentFightActivity' in value) || value['recentFightActivity'] === undefined) return false;
    if (!('performanceConsistency' in value) || value['performanceConsistency'] === undefined) return false;
    return true;
}

export function BoxerInputFromJSON(json: any): BoxerInput {
    return BoxerInputFromJSONTyped(json, false);
}

export function BoxerInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): BoxerInput {
    if (json == null) {
        return json;
    }
    return {
        
        'boxerName': json['boxerName'],
        'attributeConfidence': json['attributeConfidence'],
        'heightCm': json['heightCm'],
        'reachCm': json['reachCm'],
        'weightClassAlignment': json['weightClassAlignment'],
        'handSpeed': json['handSpeed'],
        'footSpeed': json['footSpeed'],
        'strength': json['strength'],
        'endurance': json['endurance'],
        'reactionTime': json['reactionTime'],
        'punchAccuracy': json['punchAccuracy'],
        'punchVariety': json['punchVariety'],
        'defensiveGuardEfficiency': json['defensiveGuardEfficiency'],
        'headMovement': json['headMovement'],
        'footworkTechnique': json['footworkTechnique'],
        'counterpunchingAbility': json['counterpunchingAbility'],
        'combinationEfficiency': json['combinationEfficiency'],
        'ringIq': json['ringIq'],
        'adaptabilityMidFight': json['adaptabilityMidFight'],
        'distanceControl': json['distanceControl'],
        'tempoControl': json['tempoControl'],
        'opponentPatternRecognition': json['opponentPatternRecognition'],
        'fightPlanningDiscipline': json['fightPlanningDiscipline'],
        'composureUnderPressure': json['composureUnderPressure'],
        'aggressionControl': json['aggressionControl'],
        'mentalToughness': json['mentalToughness'],
        'focusConsistency': json['focusConsistency'],
        'resilienceAfterKnockdown': json['resilienceAfterKnockdown'],
        'winRatio': json['winRatio'],
        'knockoutRatio': json['knockoutRatio'],
        'titleFightExperience': json['titleFightExperience'],
        'strengthOfOpposition': json['strengthOfOpposition'],
        'recentFightActivity': json['recentFightActivity'],
        'performanceConsistency': json['performanceConsistency'],
    };
}

export function BoxerInputToJSON(json: any): BoxerInput {
    return BoxerInputToJSONTyped(json, false);
}

export function BoxerInputToJSONTyped(value?: BoxerInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'boxerName': value['boxerName'],
        'attributeConfidence': value['attributeConfidence'],
        'heightCm': value['heightCm'],
        'reachCm': value['reachCm'],
        'weightClassAlignment': value['weightClassAlignment'],
        'handSpeed': value['handSpeed'],
        'footSpeed': value['footSpeed'],
        'strength': value['strength'],
        'endurance': value['endurance'],
        'reactionTime': value['reactionTime'],
        'punchAccuracy': value['punchAccuracy'],
        'punchVariety': value['punchVariety'],
        'defensiveGuardEfficiency': value['defensiveGuardEfficiency'],
        'headMovement': value['headMovement'],
        'footworkTechnique': value['footworkTechnique'],
        'counterpunchingAbility': value['counterpunchingAbility'],
        'combinationEfficiency': value['combinationEfficiency'],
        'ringIq': value['ringIq'],
        'adaptabilityMidFight': value['adaptabilityMidFight'],
        'distanceControl': value['distanceControl'],
        'tempoControl': value['tempoControl'],
        'opponentPatternRecognition': value['opponentPatternRecognition'],
        'fightPlanningDiscipline': value['fightPlanningDiscipline'],
        'composureUnderPressure': value['composureUnderPressure'],
        'aggressionControl': value['aggressionControl'],
        'mentalToughness': value['mentalToughness'],
        'focusConsistency': value['focusConsistency'],
        'resilienceAfterKnockdown': value['resilienceAfterKnockdown'],
        'winRatio': value['winRatio'],
        'knockoutRatio': value['knockoutRatio'],
        'titleFightExperience': value['titleFightExperience'],
        'strengthOfOpposition': value['strengthOfOpposition'],
        'recentFightActivity': value['recentFightActivity'],
        'performanceConsistency': value['performanceConsistency'],
    };
}

