/* tslint:disable */
/* eslint-disable */
/**
 * Nexus Boxing API
 * REST API for authentication, all time ranked boxers, perfect boxer generation, updating category weights, making predictions, managing prediction histories, and weight classes.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request to generate a boxer profile using AI for a given boxer name and weight class
 * @export
 * @interface GenerateBoxerProfileRequest
 */
export interface GenerateBoxerProfileRequest {
    /**
     * Name of the boxer to generate a profile for
     * @type {string}
     * @memberof GenerateBoxerProfileRequest
     */
    boxerName: string;
    /**
     * Weight class ID to contextualize the boxer profile
     * @type {number}
     * @memberof GenerateBoxerProfileRequest
     */
    weightClassId: number;
}

/**
 * Check if a given object implements the GenerateBoxerProfileRequest interface.
 */
export function instanceOfGenerateBoxerProfileRequest(value: object): value is GenerateBoxerProfileRequest {
    if (!('boxerName' in value) || value['boxerName'] === undefined) return false;
    if (!('weightClassId' in value) || value['weightClassId'] === undefined) return false;
    return true;
}

export function GenerateBoxerProfileRequestFromJSON(json: any): GenerateBoxerProfileRequest {
    return GenerateBoxerProfileRequestFromJSONTyped(json, false);
}

export function GenerateBoxerProfileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateBoxerProfileRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'boxerName': json['boxerName'],
        'weightClassId': json['weightClassId'],
    };
}

export function GenerateBoxerProfileRequestToJSON(json: any): GenerateBoxerProfileRequest {
    return GenerateBoxerProfileRequestToJSONTyped(json, false);
}

export function GenerateBoxerProfileRequestToJSONTyped(value?: GenerateBoxerProfileRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'boxerName': value['boxerName'],
        'weightClassId': value['weightClassId'],
    };
}

