/* tslint:disable */
/* eslint-disable */
/**
 * Nexus Boxing API
 * REST API for authentication, all time ranked boxers, perfect boxer generation, updating category weights, making predictions, managing prediction histories, and weight classes.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request to start perfect boxer generation for a specific weight class
 * @export
 * @interface PerfectBoxerGenerationRequest
 */
export interface PerfectBoxerGenerationRequest {
    /**
     * ID of the weight class for which the perfect boxer will be generated
     * @type {number}
     * @memberof PerfectBoxerGenerationRequest
     */
    weightClassId: number;
    /**
     * Number of top ranked boxers to use when generating the perfect boxer (used to compute mean attributes)
     * @type {number}
     * @memberof PerfectBoxerGenerationRequest
     */
    amount: number;
}

/**
 * Check if a given object implements the PerfectBoxerGenerationRequest interface.
 */
export function instanceOfPerfectBoxerGenerationRequest(value: object): value is PerfectBoxerGenerationRequest {
    if (!('weightClassId' in value) || value['weightClassId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function PerfectBoxerGenerationRequestFromJSON(json: any): PerfectBoxerGenerationRequest {
    return PerfectBoxerGenerationRequestFromJSONTyped(json, false);
}

export function PerfectBoxerGenerationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PerfectBoxerGenerationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'weightClassId': json['weightClassId'],
        'amount': json['amount'],
    };
}

export function PerfectBoxerGenerationRequestToJSON(json: any): PerfectBoxerGenerationRequest {
    return PerfectBoxerGenerationRequestToJSONTyped(json, false);
}

export function PerfectBoxerGenerationRequestToJSONTyped(value?: PerfectBoxerGenerationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'weightClassId': value['weightClassId'],
        'amount': value['amount'],
    };
}

