/* tslint:disable */
/* eslint-disable */
/**
 * Nexus Boxing API
 * REST API for authentication, all time ranked boxers, perfect boxer generation, updating category weights, making predictions, managing prediction histories, and weight classes.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response returned when perfect boxer generation has started
 * @export
 * @interface PerfectBoxerGenerationStartedResponse
 */
export interface PerfectBoxerGenerationStartedResponse {
    /**
     * Generated batch ID
     * @type {number}
     * @memberof PerfectBoxerGenerationStartedResponse
     */
    batchId?: number;
    /**
     * Weight class ID being processed
     * @type {number}
     * @memberof PerfectBoxerGenerationStartedResponse
     */
    weightClassId?: number;
    /**
     * Number of top ranked boxers requested for the generation
     * @type {number}
     * @memberof PerfectBoxerGenerationStartedResponse
     */
    amount?: number;
    /**
     * Current batch status
     * @type {string}
     * @memberof PerfectBoxerGenerationStartedResponse
     */
    status?: string;
    /**
     * User-friendly status message
     * @type {string}
     * @memberof PerfectBoxerGenerationStartedResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the PerfectBoxerGenerationStartedResponse interface.
 */
export function instanceOfPerfectBoxerGenerationStartedResponse(value: object): value is PerfectBoxerGenerationStartedResponse {
    return true;
}

export function PerfectBoxerGenerationStartedResponseFromJSON(json: any): PerfectBoxerGenerationStartedResponse {
    return PerfectBoxerGenerationStartedResponseFromJSONTyped(json, false);
}

export function PerfectBoxerGenerationStartedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PerfectBoxerGenerationStartedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'batchId': json['batchId'] == null ? undefined : json['batchId'],
        'weightClassId': json['weightClassId'] == null ? undefined : json['weightClassId'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'status': json['status'] == null ? undefined : json['status'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function PerfectBoxerGenerationStartedResponseToJSON(json: any): PerfectBoxerGenerationStartedResponse {
    return PerfectBoxerGenerationStartedResponseToJSONTyped(json, false);
}

export function PerfectBoxerGenerationStartedResponseToJSONTyped(value?: PerfectBoxerGenerationStartedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'batchId': value['batchId'],
        'weightClassId': value['weightClassId'],
        'amount': value['amount'],
        'status': value['status'],
        'message': value['message'],
    };
}

