/* tslint:disable */
/* eslint-disable */
/**
 * Nexus Boxing API
 * REST API for authentication, all time ranked boxers, perfect boxer generation, updating category weights, making predictions, managing prediction histories, and weight classes.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response containing the status of a perfect boxer generation batch
 * @export
 * @interface PerfectBoxerBatchStatusResponse
 */
export interface PerfectBoxerBatchStatusResponse {
    /**
     * Batch ID
     * @type {number}
     * @memberof PerfectBoxerBatchStatusResponse
     */
    batchId?: number;
    /**
     * Weight class ID being processed in the batch
     * @type {number}
     * @memberof PerfectBoxerBatchStatusResponse
     */
    weightClassId?: number;
    /**
     * Number of ranked boxers used for the batch
     * @type {number}
     * @memberof PerfectBoxerBatchStatusResponse
     */
    amount?: number;
    /**
     * Current batch status
     * @type {string}
     * @memberof PerfectBoxerBatchStatusResponse
     */
    status?: string;
    /**
     * Whether this batch is the currently active batch for the weight class
     * @type {boolean}
     * @memberof PerfectBoxerBatchStatusResponse
     */
    isActive?: boolean;
    /**
     * Error message if the batch failed, otherwise null
     * @type {string}
     * @memberof PerfectBoxerBatchStatusResponse
     */
    errorMessage?: string;
    /**
     * Date and time when the batch was created
     * @type {Date}
     * @memberof PerfectBoxerBatchStatusResponse
     */
    createdAt?: Date;
    /**
     * Generated perfect boxer ID if available, otherwise null
     * @type {number}
     * @memberof PerfectBoxerBatchStatusResponse
     */
    perfectBoxerId?: number;
}

/**
 * Check if a given object implements the PerfectBoxerBatchStatusResponse interface.
 */
export function instanceOfPerfectBoxerBatchStatusResponse(value: object): value is PerfectBoxerBatchStatusResponse {
    return true;
}

export function PerfectBoxerBatchStatusResponseFromJSON(json: any): PerfectBoxerBatchStatusResponse {
    return PerfectBoxerBatchStatusResponseFromJSONTyped(json, false);
}

export function PerfectBoxerBatchStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PerfectBoxerBatchStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'batchId': json['batchId'] == null ? undefined : json['batchId'],
        'weightClassId': json['weightClassId'] == null ? undefined : json['weightClassId'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'status': json['status'] == null ? undefined : json['status'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
        'errorMessage': json['errorMessage'] == null ? undefined : json['errorMessage'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'perfectBoxerId': json['perfectBoxerId'] == null ? undefined : json['perfectBoxerId'],
    };
}

export function PerfectBoxerBatchStatusResponseToJSON(json: any): PerfectBoxerBatchStatusResponse {
    return PerfectBoxerBatchStatusResponseToJSONTyped(json, false);
}

export function PerfectBoxerBatchStatusResponseToJSONTyped(value?: PerfectBoxerBatchStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'batchId': value['batchId'],
        'weightClassId': value['weightClassId'],
        'amount': value['amount'],
        'status': value['status'],
        'isActive': value['isActive'],
        'errorMessage': value['errorMessage'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'perfectBoxerId': value['perfectBoxerId'],
    };
}

