/* tslint:disable */
/* eslint-disable */
/**
 * Nexus Boxing API
 * REST API for authentication, all time ranked boxers, perfect boxer generation, updating category weights, making predictions, managing prediction histories, and weight classes.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Full perfect boxer data including all attributes
 * @export
 * @interface PerfectBoxerResponse
 */
export interface PerfectBoxerResponse {
    /**
     * 
     * @type {number}
     * @memberof PerfectBoxerResponse
     */
    perfectBoxerId?: number;
    /**
     * 
     * @type {number}
     * @memberof PerfectBoxerResponse
     */
    batchId?: number;
    /**
     * 
     * @type {number}
     * @memberof PerfectBoxerResponse
     */
    weightClassId?: number;
    /**
     * 
     * @type {number}
     * @memberof PerfectBoxerResponse
     */
    heightCm?: number;
    /**
     * 
     * @type {number}
     * @memberof PerfectBoxerResponse
     */
    reachCm?: number;
    /**
     * 
     * @type {number}
     * @memberof PerfectBoxerResponse
     */
    weightClassAlignment?: number;
    /**
     * 
     * @type {number}
     * @memberof PerfectBoxerResponse
     */
    handSpeed?: number;
    /**
     * 
     * @type {number}
     * @memberof PerfectBoxerResponse
     */
    footSpeed?: number;
    /**
     * 
     * @type {number}
     * @memberof PerfectBoxerResponse
     */
    strength?: number;
    /**
     * 
     * @type {number}
     * @memberof PerfectBoxerResponse
     */
    endurance?: number;
    /**
     * 
     * @type {number}
     * @memberof PerfectBoxerResponse
     */
    reactionTime?: number;
    /**
     * 
     * @type {number}
     * @memberof PerfectBoxerResponse
     */
    punchAccuracy?: number;
    /**
     * 
     * @type {number}
     * @memberof PerfectBoxerResponse
     */
    punchVariety?: number;
    /**
     * 
     * @type {number}
     * @memberof PerfectBoxerResponse
     */
    defensiveGuardEfficiency?: number;
    /**
     * 
     * @type {number}
     * @memberof PerfectBoxerResponse
     */
    headMovement?: number;
    /**
     * 
     * @type {number}
     * @memberof PerfectBoxerResponse
     */
    footworkTechnique?: number;
    /**
     * 
     * @type {number}
     * @memberof PerfectBoxerResponse
     */
    counterpunchingAbility?: number;
    /**
     * 
     * @type {number}
     * @memberof PerfectBoxerResponse
     */
    combinationEfficiency?: number;
    /**
     * 
     * @type {number}
     * @memberof PerfectBoxerResponse
     */
    ringIq?: number;
    /**
     * 
     * @type {number}
     * @memberof PerfectBoxerResponse
     */
    adaptabilityMidFight?: number;
    /**
     * 
     * @type {number}
     * @memberof PerfectBoxerResponse
     */
    distanceControl?: number;
    /**
     * 
     * @type {number}
     * @memberof PerfectBoxerResponse
     */
    tempoControl?: number;
    /**
     * 
     * @type {number}
     * @memberof PerfectBoxerResponse
     */
    opponentPatternRecognition?: number;
    /**
     * 
     * @type {number}
     * @memberof PerfectBoxerResponse
     */
    fightPlanningDiscipline?: number;
    /**
     * 
     * @type {number}
     * @memberof PerfectBoxerResponse
     */
    composureUnderPressure?: number;
    /**
     * 
     * @type {number}
     * @memberof PerfectBoxerResponse
     */
    aggressionControl?: number;
    /**
     * 
     * @type {number}
     * @memberof PerfectBoxerResponse
     */
    mentalToughness?: number;
    /**
     * 
     * @type {number}
     * @memberof PerfectBoxerResponse
     */
    focusConsistency?: number;
    /**
     * 
     * @type {number}
     * @memberof PerfectBoxerResponse
     */
    resilienceAfterKnockdown?: number;
    /**
     * 
     * @type {number}
     * @memberof PerfectBoxerResponse
     */
    winRatio?: number;
    /**
     * 
     * @type {number}
     * @memberof PerfectBoxerResponse
     */
    knockoutRatio?: number;
    /**
     * 
     * @type {number}
     * @memberof PerfectBoxerResponse
     */
    titleFightExperience?: number;
    /**
     * 
     * @type {number}
     * @memberof PerfectBoxerResponse
     */
    strengthOfOpposition?: number;
    /**
     * 
     * @type {number}
     * @memberof PerfectBoxerResponse
     */
    recentFightActivity?: number;
    /**
     * 
     * @type {number}
     * @memberof PerfectBoxerResponse
     */
    performanceConsistency?: number;
    /**
     * 
     * @type {Date}
     * @memberof PerfectBoxerResponse
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PerfectBoxerResponse
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the PerfectBoxerResponse interface.
 */
export function instanceOfPerfectBoxerResponse(value: object): value is PerfectBoxerResponse {
    return true;
}

export function PerfectBoxerResponseFromJSON(json: any): PerfectBoxerResponse {
    return PerfectBoxerResponseFromJSONTyped(json, false);
}

export function PerfectBoxerResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PerfectBoxerResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'perfectBoxerId': json['perfectBoxerId'] == null ? undefined : json['perfectBoxerId'],
        'batchId': json['batchId'] == null ? undefined : json['batchId'],
        'weightClassId': json['weightClassId'] == null ? undefined : json['weightClassId'],
        'heightCm': json['heightCm'] == null ? undefined : json['heightCm'],
        'reachCm': json['reachCm'] == null ? undefined : json['reachCm'],
        'weightClassAlignment': json['weightClassAlignment'] == null ? undefined : json['weightClassAlignment'],
        'handSpeed': json['handSpeed'] == null ? undefined : json['handSpeed'],
        'footSpeed': json['footSpeed'] == null ? undefined : json['footSpeed'],
        'strength': json['strength'] == null ? undefined : json['strength'],
        'endurance': json['endurance'] == null ? undefined : json['endurance'],
        'reactionTime': json['reactionTime'] == null ? undefined : json['reactionTime'],
        'punchAccuracy': json['punchAccuracy'] == null ? undefined : json['punchAccuracy'],
        'punchVariety': json['punchVariety'] == null ? undefined : json['punchVariety'],
        'defensiveGuardEfficiency': json['defensiveGuardEfficiency'] == null ? undefined : json['defensiveGuardEfficiency'],
        'headMovement': json['headMovement'] == null ? undefined : json['headMovement'],
        'footworkTechnique': json['footworkTechnique'] == null ? undefined : json['footworkTechnique'],
        'counterpunchingAbility': json['counterpunchingAbility'] == null ? undefined : json['counterpunchingAbility'],
        'combinationEfficiency': json['combinationEfficiency'] == null ? undefined : json['combinationEfficiency'],
        'ringIq': json['ringIq'] == null ? undefined : json['ringIq'],
        'adaptabilityMidFight': json['adaptabilityMidFight'] == null ? undefined : json['adaptabilityMidFight'],
        'distanceControl': json['distanceControl'] == null ? undefined : json['distanceControl'],
        'tempoControl': json['tempoControl'] == null ? undefined : json['tempoControl'],
        'opponentPatternRecognition': json['opponentPatternRecognition'] == null ? undefined : json['opponentPatternRecognition'],
        'fightPlanningDiscipline': json['fightPlanningDiscipline'] == null ? undefined : json['fightPlanningDiscipline'],
        'composureUnderPressure': json['composureUnderPressure'] == null ? undefined : json['composureUnderPressure'],
        'aggressionControl': json['aggressionControl'] == null ? undefined : json['aggressionControl'],
        'mentalToughness': json['mentalToughness'] == null ? undefined : json['mentalToughness'],
        'focusConsistency': json['focusConsistency'] == null ? undefined : json['focusConsistency'],
        'resilienceAfterKnockdown': json['resilienceAfterKnockdown'] == null ? undefined : json['resilienceAfterKnockdown'],
        'winRatio': json['winRatio'] == null ? undefined : json['winRatio'],
        'knockoutRatio': json['knockoutRatio'] == null ? undefined : json['knockoutRatio'],
        'titleFightExperience': json['titleFightExperience'] == null ? undefined : json['titleFightExperience'],
        'strengthOfOpposition': json['strengthOfOpposition'] == null ? undefined : json['strengthOfOpposition'],
        'recentFightActivity': json['recentFightActivity'] == null ? undefined : json['recentFightActivity'],
        'performanceConsistency': json['performanceConsistency'] == null ? undefined : json['performanceConsistency'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function PerfectBoxerResponseToJSON(json: any): PerfectBoxerResponse {
    return PerfectBoxerResponseToJSONTyped(json, false);
}

export function PerfectBoxerResponseToJSONTyped(value?: PerfectBoxerResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'perfectBoxerId': value['perfectBoxerId'],
        'batchId': value['batchId'],
        'weightClassId': value['weightClassId'],
        'heightCm': value['heightCm'],
        'reachCm': value['reachCm'],
        'weightClassAlignment': value['weightClassAlignment'],
        'handSpeed': value['handSpeed'],
        'footSpeed': value['footSpeed'],
        'strength': value['strength'],
        'endurance': value['endurance'],
        'reactionTime': value['reactionTime'],
        'punchAccuracy': value['punchAccuracy'],
        'punchVariety': value['punchVariety'],
        'defensiveGuardEfficiency': value['defensiveGuardEfficiency'],
        'headMovement': value['headMovement'],
        'footworkTechnique': value['footworkTechnique'],
        'counterpunchingAbility': value['counterpunchingAbility'],
        'combinationEfficiency': value['combinationEfficiency'],
        'ringIq': value['ringIq'],
        'adaptabilityMidFight': value['adaptabilityMidFight'],
        'distanceControl': value['distanceControl'],
        'tempoControl': value['tempoControl'],
        'opponentPatternRecognition': value['opponentPatternRecognition'],
        'fightPlanningDiscipline': value['fightPlanningDiscipline'],
        'composureUnderPressure': value['composureUnderPressure'],
        'aggressionControl': value['aggressionControl'],
        'mentalToughness': value['mentalToughness'],
        'focusConsistency': value['focusConsistency'],
        'resilienceAfterKnockdown': value['resilienceAfterKnockdown'],
        'winRatio': value['winRatio'],
        'knockoutRatio': value['knockoutRatio'],
        'titleFightExperience': value['titleFightExperience'],
        'strengthOfOpposition': value['strengthOfOpposition'],
        'recentFightActivity': value['recentFightActivity'],
        'performanceConsistency': value['performanceConsistency'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

