/* tslint:disable */
/* eslint-disable */
/**
 * Nexus Boxing API
 * REST API for authentication, all time ranked boxers, perfect boxer generation, updating category weights, making predictions, managing prediction histories, and weight classes.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PredictionResponse
 */
export interface PredictionResponse {
    /**
     * 
     * @type {number}
     * @memberof PredictionResponse
     */
    predictionId?: number;
    /**
     * 
     * @type {string}
     * @memberof PredictionResponse
     */
    boxerAName?: string;
    /**
     * 
     * @type {string}
     * @memberof PredictionResponse
     */
    boxerBName?: string;
    /**
     * 
     * @type {string}
     * @memberof PredictionResponse
     */
    predictedWinner?: string;
    /**
     * 
     * @type {number}
     * @memberof PredictionResponse
     */
    weightClassId?: number;
    /**
     * 
     * @type {number}
     * @memberof PredictionResponse
     */
    closenessA?: number;
    /**
     * 
     * @type {number}
     * @memberof PredictionResponse
     */
    closenessB?: number;
    /**
     * 
     * @type {number}
     * @memberof PredictionResponse
     */
    probabilityA?: number;
    /**
     * 
     * @type {number}
     * @memberof PredictionResponse
     */
    probabilityB?: number;
    /**
     * 
     * @type {string}
     * @memberof PredictionResponse
     */
    explanation?: string;
    /**
     * 
     * @type {Date}
     * @memberof PredictionResponse
     */
    predictionDate?: Date;
}

/**
 * Check if a given object implements the PredictionResponse interface.
 */
export function instanceOfPredictionResponse(value: object): value is PredictionResponse {
    return true;
}

export function PredictionResponseFromJSON(json: any): PredictionResponse {
    return PredictionResponseFromJSONTyped(json, false);
}

export function PredictionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PredictionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'predictionId': json['predictionId'] == null ? undefined : json['predictionId'],
        'boxerAName': json['boxerAName'] == null ? undefined : json['boxerAName'],
        'boxerBName': json['boxerBName'] == null ? undefined : json['boxerBName'],
        'predictedWinner': json['predictedWinner'] == null ? undefined : json['predictedWinner'],
        'weightClassId': json['weightClassId'] == null ? undefined : json['weightClassId'],
        'closenessA': json['closenessA'] == null ? undefined : json['closenessA'],
        'closenessB': json['closenessB'] == null ? undefined : json['closenessB'],
        'probabilityA': json['probabilityA'] == null ? undefined : json['probabilityA'],
        'probabilityB': json['probabilityB'] == null ? undefined : json['probabilityB'],
        'explanation': json['explanation'] == null ? undefined : json['explanation'],
        'predictionDate': json['predictionDate'] == null ? undefined : (new Date(json['predictionDate'])),
    };
}

export function PredictionResponseToJSON(json: any): PredictionResponse {
    return PredictionResponseToJSONTyped(json, false);
}

export function PredictionResponseToJSONTyped(value?: PredictionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'predictionId': value['predictionId'],
        'boxerAName': value['boxerAName'],
        'boxerBName': value['boxerBName'],
        'predictedWinner': value['predictedWinner'],
        'weightClassId': value['weightClassId'],
        'closenessA': value['closenessA'],
        'closenessB': value['closenessB'],
        'probabilityA': value['probabilityA'],
        'probabilityB': value['probabilityB'],
        'explanation': value['explanation'],
        'predictionDate': value['predictionDate'] == null ? value['predictionDate'] : value['predictionDate'].toISOString(),
    };
}

