/* tslint:disable */
/* eslint-disable */
/**
 * Nexus Boxing API
 * REST API for authentication, all time ranked boxers, perfect boxer generation, updating category weights, making predictions, managing prediction histories, and weight classes.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PredictionResultUpdateRequest
 */
export interface PredictionResultUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof PredictionResultUpdateRequest
     */
    matchWinner?: string;
    /**
     * 
     * @type {string}
     * @memberof PredictionResultUpdateRequest
     */
    matchWinMethod?: string;
}

/**
 * Check if a given object implements the PredictionResultUpdateRequest interface.
 */
export function instanceOfPredictionResultUpdateRequest(value: object): value is PredictionResultUpdateRequest {
    return true;
}

export function PredictionResultUpdateRequestFromJSON(json: any): PredictionResultUpdateRequest {
    return PredictionResultUpdateRequestFromJSONTyped(json, false);
}

export function PredictionResultUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PredictionResultUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'matchWinner': json['matchWinner'] == null ? undefined : json['matchWinner'],
        'matchWinMethod': json['matchWinMethod'] == null ? undefined : json['matchWinMethod'],
    };
}

export function PredictionResultUpdateRequestToJSON(json: any): PredictionResultUpdateRequest {
    return PredictionResultUpdateRequestToJSONTyped(json, false);
}

export function PredictionResultUpdateRequestToJSONTyped(value?: PredictionResultUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'matchWinner': value['matchWinner'],
        'matchWinMethod': value['matchWinMethod'],
    };
}

