/* tslint:disable */
/* eslint-disable */
/**
 * Nexus Boxing API
 * REST API for authentication, all time ranked boxers, perfect boxer generation, updating category weights, making predictions, managing prediction histories, and weight classes.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Prediction history response
 * @export
 * @interface PredictionHistoryResponse
 */
export interface PredictionHistoryResponse {
    /**
     * Unique prediction ID
     * @type {number}
     * @memberof PredictionHistoryResponse
     */
    predictionId?: number;
    /**
     * Name of boxer A
     * @type {string}
     * @memberof PredictionHistoryResponse
     */
    boxerAName?: string;
    /**
     * Name of boxer B
     * @type {string}
     * @memberof PredictionHistoryResponse
     */
    boxerBName?: string;
    /**
     * Model-predicted winner
     * @type {string}
     * @memberof PredictionHistoryResponse
     */
    predictedWinner?: string;
    /**
     * Actual winner after the fight, if known
     * @type {string}
     * @memberof PredictionHistoryResponse
     */
    matchWinner?: string;
    /**
     * Actual method of victory, if known
     * @type {string}
     * @memberof PredictionHistoryResponse
     */
    matchWinMethod?: string;
    /**
     * Weight class ID
     * @type {number}
     * @memberof PredictionHistoryResponse
     */
    weightClassId?: number;
    /**
     * Closeness score of boxer A to the perfect boxer
     * @type {number}
     * @memberof PredictionHistoryResponse
     */
    boxerAClosenessScore?: number;
    /**
     * Closeness score of boxer B to the perfect boxer
     * @type {number}
     * @memberof PredictionHistoryResponse
     */
    boxerBClosenessScore?: number;
    /**
     * Predicted win probability for boxer A
     * @type {number}
     * @memberof PredictionHistoryResponse
     */
    probabilityA?: number;
    /**
     * Predicted win probability for boxer B
     * @type {number}
     * @memberof PredictionHistoryResponse
     */
    probabilityB?: number;
    /**
     * Detailed structured breakdown or explanation of the prediction
     * @type {{ [key: string]: object; }}
     * @memberof PredictionHistoryResponse
     */
    breakdownSnapshot?: { [key: string]: object; };
    /**
     * Date and time of prediction
     * @type {Date}
     * @memberof PredictionHistoryResponse
     */
    predictionDate?: Date;
}

/**
 * Check if a given object implements the PredictionHistoryResponse interface.
 */
export function instanceOfPredictionHistoryResponse(value: object): value is PredictionHistoryResponse {
    return true;
}

export function PredictionHistoryResponseFromJSON(json: any): PredictionHistoryResponse {
    return PredictionHistoryResponseFromJSONTyped(json, false);
}

export function PredictionHistoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PredictionHistoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'predictionId': json['predictionId'] == null ? undefined : json['predictionId'],
        'boxerAName': json['boxerAName'] == null ? undefined : json['boxerAName'],
        'boxerBName': json['boxerBName'] == null ? undefined : json['boxerBName'],
        'predictedWinner': json['predictedWinner'] == null ? undefined : json['predictedWinner'],
        'matchWinner': json['matchWinner'] == null ? undefined : json['matchWinner'],
        'matchWinMethod': json['matchWinMethod'] == null ? undefined : json['matchWinMethod'],
        'weightClassId': json['weightClassId'] == null ? undefined : json['weightClassId'],
        'boxerAClosenessScore': json['boxerAClosenessScore'] == null ? undefined : json['boxerAClosenessScore'],
        'boxerBClosenessScore': json['boxerBClosenessScore'] == null ? undefined : json['boxerBClosenessScore'],
        'probabilityA': json['probabilityA'] == null ? undefined : json['probabilityA'],
        'probabilityB': json['probabilityB'] == null ? undefined : json['probabilityB'],
        'breakdownSnapshot': json['breakdownSnapshot'] == null ? undefined : json['breakdownSnapshot'],
        'predictionDate': json['predictionDate'] == null ? undefined : (new Date(json['predictionDate'])),
    };
}

export function PredictionHistoryResponseToJSON(json: any): PredictionHistoryResponse {
    return PredictionHistoryResponseToJSONTyped(json, false);
}

export function PredictionHistoryResponseToJSONTyped(value?: PredictionHistoryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'predictionId': value['predictionId'],
        'boxerAName': value['boxerAName'],
        'boxerBName': value['boxerBName'],
        'predictedWinner': value['predictedWinner'],
        'matchWinner': value['matchWinner'],
        'matchWinMethod': value['matchWinMethod'],
        'weightClassId': value['weightClassId'],
        'boxerAClosenessScore': value['boxerAClosenessScore'],
        'boxerBClosenessScore': value['boxerBClosenessScore'],
        'probabilityA': value['probabilityA'],
        'probabilityB': value['probabilityB'],
        'breakdownSnapshot': value['breakdownSnapshot'],
        'predictionDate': value['predictionDate'] == null ? value['predictionDate'] : value['predictionDate'].toISOString(),
    };
}

